import { bullets, cover, portrait, type Persona } from './types';

/**
 * Kian Rahmani — back-end engineer working on payments and event pipelines.
 *
 * Same career, opposite surface: less about pixels, more about contracts,
 * consistency and what happens at 3 a.m. on a peak day.
 */
export const backend: Persona = {
  id: 'backend',
  label: 'Back-end engineer · payments & event pipelines',

  profile: {
    en: [
      {
        name: 'Kian',
        fullName: 'Kian Rahmani',
        jobTitle: 'Back-end Engineer · Distributed Systems',
        summary:
          'I design the parts users never see: API contracts, event pipelines and databases that stay correct under load and honest when they fail.',
        description: [
          'Nine years of server-side work: payment switches, settlement, and rather a lot of message queues. I build the unglamorous layer — APIs with stable contracts, pipelines that tolerate redelivery, and stores that stay correct at three in the morning on a peak day.',
          '',
          'Most of my value is in what does **not** break. At **Zarch Platform** I own the settlement service that moves roughly forty billion tomans a day. It has run fourteen months without a customer-visible incident, which is the proudest number on this page.',
          '',
          '### How I work',
          '',
          '- Model the domain before the framework, and the migration before the model',
          '- Idempotency and retry policy are design decisions, not bug fixes',
          '- Observability ships with the feature: a metric without an owner is decoration',
          '- A written RFC beats a remembered decision',
          '',
          'Off hours I read database internals, maintain a small Go library for transactional outbox, and argue about Kafka partition counts in a Telegram group with old classmates.',
        ].join('\n'),
        avatarUrl: portrait('kian-rahmani'),
        tel: '+98 916 222 0341',
        email: 'kian@rahmani.dev',
      },
    ],
    fa: [
      {
        name: 'کیان',
        fullName: 'کیان رحمانی',
        jobTitle: 'مهندس بک‌اند · سیستم‌های توزیع‌شده',
        summary:
          'بخش‌هایی را طراحی می‌کنم که کاربر هیچ‌وقت نمی‌بیند: قرارداد API، پایپ‌لاین رویداد و دیتابیس‌هایی که زیر بار درست می‌مانند و هنگام خطا صادق‌اند.',
        description: [
          'نه سال کار سمت سرور: سوییچ پرداخت، تسویه و تعداد زیادی صف پیام. من لایه بی‌جلوه را می‌سازم؛ API با قرارداد پایدار، پایپ‌لاینی که دوباره‌تحویل را تحمل می‌کند و ذخیره‌ای که ساعت سه بامداد یک روز شلوغ هم درست می‌ماند.',
          '',
          'بیشتر ارزش من در چیزی است که **نمی‌شکند**. در **پلتفرم زارچ** سرویس تسویه را نگه می‌دارم که روزانه حدود چهل میلیارد تومان را جابه‌جا می‌کند؛ چهارده ماه بدون هیچ رخداد قابل‌مشاهده برای مشتری کار کرده و این برجسته‌ترین عدد این صفحه است.',
          '',
          '### چطور کار می‌کنم',
          '',
          '- اول دامنه را مدل می‌کنم، بعد فریمورک را؛ و مهاجرت را قبل از مدل می‌نویسم',
          '- idempotency و سیاست retry تصمیم طراحی‌اند، نه اصلاح باگ',
          '- مشاهده‌پذیری همراه فیچر منتشر می‌شود: متریک بی‌مالک، تزئینات است',
          '- یک RFC نوشته‌شده بر تصمیم به‌خاطرمانده می‌چربد',
          '',
          'خارج از ساعت کاری، internals دیتابیس می‌خوانم، یک کتابخانه کوچک Go برای الگوی transactional outbox نگه می‌دارم و در یک گروه تلگرامی با هم‌کلاسی‌های قدیمی درباره تعداد پارتیشن‌های Kafka بحث می‌کنم.',
        ].join('\n'),
        avatarUrl: portrait('kian-rahmani'),
        tel: '۰۹۱۶ ۲۲۲ ۰۳۴۱',
        email: 'kian@rahmani.dev',
      },
    ],
  },

  socials: {
    en: [
      { name: 'GitHub', url: 'https://github.com/kianrahmani', icon: 'github' },
      { name: 'LinkedIn', url: 'https://www.linkedin.com/in/kian-rahmani', icon: 'linkedin' },
      { name: 'X', url: 'https://x.com/kian_builds', icon: 'x' },
      { name: 'Telegram', url: 'https://t.me/kian_backend', icon: 'telegram' },
    ],
    fa: [
      { name: 'گیت‌هاب', url: 'https://github.com/kianrahmani', icon: 'github' },
      { name: 'لینکدین', url: 'https://www.linkedin.com/in/kian-rahmani', icon: 'linkedin' },
      { name: 'ایکس', url: 'https://x.com/kian_builds', icon: 'x' },
      { name: 'تلگرام', url: 'https://t.me/kian_backend', icon: 'telegram' },
    ],
  },

  skills: {
    en: [
      { name: 'Go' },
      { name: 'Node.js' },
      { name: 'TypeScript' },
      { name: 'PostgreSQL' },
      { name: 'Redis' },
      { name: 'Apache Kafka' },
      { name: 'gRPC' },
      { name: 'REST APIs' },
      { name: 'GraphQL' },
      { name: 'MongoDB' },
      { name: 'Docker' },
      { name: 'Kubernetes' },
      { name: 'Terraform' },
      { name: 'OpenTelemetry' },
      { name: 'Event-driven design' },
      { name: 'Database migrations' },
    ],
    fa: [
      { name: 'Go' },
      { name: 'Node.js' },
      { name: 'TypeScript' },
      { name: 'PostgreSQL' },
      { name: 'Redis' },
      { name: 'Apache Kafka' },
      { name: 'gRPC' },
      { name: 'REST API' },
      { name: 'GraphQL' },
      { name: 'MongoDB' },
      { name: 'Docker' },
      { name: 'Kubernetes' },
      { name: 'Terraform' },
      { name: 'OpenTelemetry' },
      { name: 'معماری رویدادمحور' },
      { name: 'مهاجرت دیتابیس' },
    ],
  },

  educations: {
    en: [
      {
        school: 'Sharif University of Technology',
        degree: 'M.Sc. Computer Science — Software Systems',
        href: 'https://sharif.edu',
        logoUrl: '',
        start: '2016/09',
        end: '2018/07',
      },
      {
        school: 'Isfahan University of Technology',
        degree: 'B.Sc. Computer Engineering',
        href: 'https://iut.ac.ir',
        logoUrl: '',
        start: '2012/09',
        end: '2016/07',
      },
    ],
    fa: [
      {
        school: 'دانشگاه صنعتی شریف',
        degree: 'کارشناسی ارشد مهندسی کامپیوتر — سیستم‌های نرم‌افزار',
        href: 'https://sharif.edu',
        logoUrl: '',
        start: '1395/06',
        end: '1397/04',
      },
      {
        school: 'دانشگاه صنعتی اصفهان',
        degree: 'کارشناسی مهندسی کامپیوتر',
        href: 'https://iut.ac.ir',
        logoUrl: '',
        start: '1391/06',
        end: '1395/04',
      },
    ],
  },

  works: {
    en: [
      {
        company: 'Zarch Platform',
        title: 'Lead Back-end Engineer · Settlement',
        location: 'Tehran, Iran · Hybrid',
        href: 'https://zarch.example.com',
        logoUrl: '',
        start: '2023/06',
        end: '',
        description: bullets(
          'Own the settlement service moving ~40B tomans a day across 900 merchant accounts.',
          'Replaced nightly batch reconciliation with an event pipeline: settlement lag went from 19 hours to 90 seconds.',
          'Introduced the RFC/ADR process; breaking API changes to merchant-facing endpoints are effectively zero.',
          'Cut infrastructure spend 38% by right-sizing Kafka partitions and Postgres connection pools.',
          'Mentor three engineers; run the on-call rotation and the postmortem practice.'
        ),
      },
      {
        company: 'Hamrah Pay',
        title: 'Back-end Developer',
        location: 'Tehran, Iran',
        href: 'https://hamrahpay.example.com',
        logoUrl: '',
        start: '2020/10',
        end: '2023/05',
        description: bullets(
          'Built the double-entry ledger service that every transfer, refund and fee runs through.',
          'Kept a PCI-style switch healthy at a 2,400 TPS peak with idempotent, replayable commands.',
          'Dropped p95 transfer latency from 320ms to 90ms by killing a chatty ORM and adding two indexes.'
        ),
      },
      {
        company: 'Asan Payar',
        title: 'Software Engineer · Back-end',
        location: 'Isfahan, Iran',
        href: 'https://asanpayar.example.com',
        logoUrl: '',
        start: '2018/04',
        end: '2020/09',
        description: bullets(
          'Split a Django monolith into four Go services along the billing, wallet, ledger and notification seams.',
          'Wrote the zero-downtime migration playbook still used by the team.',
          'First contact with an incident that cost real money — and the alert that should have caught it.'
        ),
      },
      {
        company: 'HPC Lab, Isfahan University of Technology',
        title: 'Research Assistant',
        location: 'Isfahan, Iran',
        href: 'https://iut.ac.ir',
        logoUrl: '',
        start: '2016/09',
        end: '2018/02',
        description: bullets(
          'Batch job scheduling and benchmarking on a 64-node cluster.',
          'Published a workshop paper on I/O contention in mixed workloads.'
        ),
      },
    ],
    fa: [
      {
        company: 'پلتفرم زارچ',
        title: 'سرپرست بک‌اند · تسویه',
        location: 'تهران، ایران · هیبرید',
        href: 'https://zarch.example.com',
        logoUrl: '',
        start: '1402/03',
        end: '',
        description: bullets(
          'مالکیت سرویس تسویه که روزانه حدود ۴۰ میلیارد تومان را بین ۹۰۰ حساب پذیرنده جابه‌جا می‌کند.',
          'جایگزینی تسویه شبانه batch با یک پایپ‌لاین رویداد؛ تأخیر تسویه از ۱۹ ساعت به ۹۰ ثانیه رسید.',
          'راه‌اندازی فرایند RFC/ADR؛ تغییرات شکنده در endpoint پذیرنده‌محور عملاً به صفر رسید.',
          'کاهش ۳۸ درصدی هزینه زیرساخت با تنظیم تعداد پارتیشن Kafka و استخر اتصال Postgres.',
          'منتورینگ سه مهندس؛ گردشی بودنِ on-call و تمرین postmortem.'
        ),
      },
      {
        company: 'همراه پی',
        title: 'توسعه‌دهنده بک‌اند',
        location: 'تهران، ایران',
        href: 'https://hamrahpay.example.com',
        logoUrl: '',
        start: '1399/07',
        end: '1402/02',
        description: bullets(
          'ساخت سرویس دفتر کل دوبل‌انتی که هر انتقال، بازگشت وجه و کارمزد از آن رد می‌شود.',
          'نگه‌داشتن سلامت سوییچ در اوج ۲٬۴۰۰ تراکنش در ثانیه با فرمان‌های idempotent و قابل پخش دوباره.',
          'کاهش تأخیر p95 انتقال از ۳۲۰ به ۹۰ میلی‌ثانیه، با حذف یک ORM پرحرف و افزودن دو ایندکس.'
        ),
      },
      {
        company: 'آسان پیار',
        title: 'مهندس نرم‌افزار · بک‌اند',
        location: 'اصفهان، ایران',
        href: 'https://asanpayar.example.com',
        logoUrl: '',
        start: '1397/01',
        end: '1399/06',
        description: bullets(
          'شکستن یک monolith در Django به چهار سرویس Go روی درزهای صورتحساب، کیف پول، دفتر کل و اعلان.',
          'نوشتن playbook مهاجرت بدون قطعی که تیم هنوز از آن استفاده می‌کند.',
          'اولین مواجهه با رخدادی که هزینه واقعی داشت — و آن alarm که باید زودتر می‌گرفت.'
        ),
      },
      {
        company: 'آزمایشگاه HPC دانشگاه صنعتی اصفهان',
        title: 'دستیار پژوهشی',
        location: 'اصفهان، ایران',
        href: 'https://iut.ac.ir',
        logoUrl: '',
        start: '1395/06',
        end: '1396/11',
        description: bullets('زمان‌بندی کارهای batch و بنچمارک روی یک خوشه ۶۴گره‌ای.', 'انتشار یک مقاله کارگاهی درباره رقابت I/O در بارهای مختلط.'),
      },
    ],
  },

  projects: {
    en: [
      {
        title: 'outbox-go',
        slug: 'outbox-go',
        href: 'https://github.com/kianrahmani/outbox-go',
        dates: 'October 2025 - Present',
        active: true,
        featured: true,
        createdAt: '2026-03-22T08:00:00.000Z',
        image: cover('outbox-go-library'),
        description:
          'A small Go library for the transactional outbox pattern: publish domain events in the same transaction as the write, and never lose one to a broker outage.',
        technologies: ['Go', 'PostgreSQL', 'Kafka', 'OpenTelemetry'],
        links: [
          { type: 'Source', href: 'https://github.com/kianrahmani/outbox-go', icon: 'github' },
          { type: 'Docs', href: 'https://outbox-go.example.com', icon: 'docs' },
        ],
        details: [
          '## The bug this exists to prevent',
          '',
          'The pattern appears in every codebase I have worked on: write to the database, then publish to the broker. It works in staging and fails in production, because the second call is not covered by the first transaction. One broker timeout and the ledger says "settled" while the notification service says nothing.',
          '',
          '## How it works',
          '',
          '1. Domain events are inserted into an `outbox_events` table **inside the same transaction** as the state change.',
          '2. A poller (or a PostgreSQL `LISTEN` trigger) drains the table into Kafka with a per-aggregate sequence, so ordering is preserved per key rather than per partition.',
          '3. Consumers deduplicate on `(aggregate_id, seq)`, which makes redelivery safe by construction.',
          '',
          '```go',
          'tx.Begin()',
          'if err := ledger.Debit(tx, cmd); err != nil {',
          '  tx.Rollback()',
          '  return err',
          '}',
          '',
          '// same transaction, same guarantees',
          'outbox.Emit(ctx, tx, AccountDebited{ID: cmd.AccountID, Amount: cmd.Amount})',
          'return tx.Commit()',
          '```',
          '',
          '## What is deliberately missing',
          '',
          'No framework, no DI, no code generation, no opinion about your schema beyond two columns. It is 900 lines and the whole test suite runs against a real PostgreSQL in CI.',
          '',
          '## Numbers',
          '',
          '| Measure | Result |',
          '| --- | --- |',
          '| Stars | 1,240 |',
          '| Reported production users | 60+ |',
          '| Events published at peak (single node) | 12k/s |',
          '| Lost events since 1.0.0 | 0 |',
          '',
          '## Stack',
          '',
          'Go 1.23, pgx, confluent-kafka-go, OpenTelemetry spans, testcontainers for integration tests.',
        ].join('\n'),
      },
      {
        title: 'Settlement Pipeline',
        slug: 'settlement-pipeline',
        href: 'https://zarch.example.com/settlement',
        dates: 'January 2024 - October 2024',
        active: true,
        featured: true,
        createdAt: '2024-11-06T08:00:00.000Z',
        image: cover('settlement-pipeline'),
        description:
          'The nightly settlement batch rebuilt as an event-driven pipeline: money moves in near real time and reconciliation is a query instead of a war room.',
        technologies: ['Go', 'Kafka', 'PostgreSQL', 'Kubernetes', 'gRPC', 'ClickHouse'],
        links: [
          { type: 'Docs', href: 'https://zarch.example.com/settlement/docs', icon: 'docs' },
          { type: 'Website', href: 'https://zarch.example.com/settlement', icon: 'website' },
        ],
        details: [
          '## Before',
          '',
          'Settlement ran as a 02:00 batch job: eight hours of SQL, a team watching progress bars, and a rollback plan that meant "do not settle today". Merchants were told their money would arrive tomorrow, and the only honest answer was "maybe the day after".',
          '',
          '## After',
          '',
          '- Every capture, refund and fee is an event on a compacted topic keyed by settlement group.',
          '- A stateful Go consumer maintains running balances in RocksDB and emits a settlement statement the moment the cutoff passes.',
          '- Reconciliation is a materialised view joined against the bank file — an alert instead of a spreadsheet, and discrepancies are named within minutes.',
          '- Replay is a first-class operation: a new topic, a from-scratch consumer group, three hours to rebuild state instead of two days.',
          '',
          '```sql',
          '-- The query that replaced the war room',
          'SELECT s.settlement_id, s.expected, b.deposited',
          'FROM settlement_statements s',
          'FULL JOIN bank_deposits b USING (settlement_id)',
          'WHERE abs(s.expected - b.deposited) > 1',
          '  OR s.settlement_id IS NULL OR b.settlement_id IS NULL;',
          '```',
          '',
          '## Results',
          '',
          '| Measure | Batch | Pipeline |',
          '| --- | --- | --- |',
          '| Settlement lag | 19 h | 90 s |',
          '| Discrepancy detection | next morning | 4 min |',
          '| Support tickets about money | 310/mo | 74/mo |',
          '| On-call pages at night | 11/mo | 2/mo |',
          '',
          '## The honest part',
          '',
          'Two things nearly killed it. First, an out-of-order bank file that double-settled one merchant for 90 minutes before the alert fired — the fix was an idempotency key on the deposit side, not a smarter consumer. Second, cost: a stateful consumer is not free, and we bought a 20% infrastructure increase before we earned it back by deleting the batch cluster.',
          '',
          '## Stack',
          '',
          'Go, Kafka (compacted topics, exactly-once producer), RocksDB, PostgreSQL, ClickHouse for analytics, Kubernetes, Grafana and OpenTelemetry.',
        ].join('\n'),
      },
      {
        title: 'Switch Observability Stack',
        slug: 'switch-observability-stack',
        href: 'https://hamrahpay.example.com/observability',
        dates: 'November 2023 - May 2024',
        active: true,
        featured: true,
        createdAt: '2024-06-10T08:00:00.000Z',
        image: cover('switch-observability'),
        description:
          "Tracing, RED metrics and business-level SLOs for a payment switch that used to be debugged by reading logs over someone's shoulder.",
        technologies: ['OpenTelemetry', 'Grafana', 'Prometheus', 'Go', 'Loki'],
        links: [
          { type: 'Docs', href: 'https://hamrahpay.example.com/observability/docs', icon: 'docs' },
          { type: 'Source', href: 'https://github.com/kianrahmani/switch-otel', icon: 'github' },
        ],
        details: [
          '## What we had',
          '',
          'A dashboard of CPU and memory, an ELK installation nobody trusted, and an on-call process that began with "which merchant is it?". Latency was measured at the edge, so we could not tell whether our switch was slow or the bank upstream was.',
          '',
          '## What we built',
          '',
          '- **One trace per transfer**, from the API gateway through risk, the ledger and the bank adapter, with the upstream response time as an explicit span attribute.',
          '- **RED metrics per issuer and per BIN**, so "cards from bank X are failing" became a graph rather than a rumour.',
          '- **Business SLOs**: 99.5% of transfers approved under 1.5s, measured end to end, paging only on the burn rate — two fast windows, 5m and 1h.',
          '- **Cardinality discipline**: no merchant id on metrics, only on logs, correlated by trace id.',
          '',
          '## Results',
          '',
          '| Measure | Before | After |',
          '| --- | --- | --- |',
          '| Median time to root cause | 47 min | 6 min |',
          '| Pages outside business hours | 23/mo | 7/mo |',
          '| "Bank is slow" disputes | 9/mo | 0 (the trace says who) |',
          '',
          '## Stack',
          '',
          'OpenTelemetry Go SDK and collector, Prometheus, Grafana, Loki, Alertmanager. The SLO math is a recorded-rules file anyone on the team can read.',
        ].join('\n'),
      },
      {
        title: 'Ledger Service',
        slug: 'ledger-service',
        href: 'https://hamrahpay.example.com/ledger',
        dates: 'February 2022 - September 2022',
        active: true,
        featured: false,
        createdAt: '2022-10-05T08:00:00.000Z',
        image: cover('ledger-service'),
        description:
          'A double-entry ledger every transfer, refund and fee runs through: append-only, replayable, and the only source of truth for how much money we hold.',
        technologies: ['Go', 'PostgreSQL', 'gRPC', 'Kafka'],
        links: [{ type: 'Source', href: 'https://github.com/kianrahmani/ledger', icon: 'github' }],
        details: [
          '## Why double-entry',
          '',
          'A `balance` column is a summary of a story nobody wrote down. Once money moved between wallets, fees and settlement, the team spent more time reconciling balances than shipping. The ledger made the rule explicit: every amount leaves one account and enters another, and the two always agree.',
          '',
          '## Rules the service enforces',
          '',
          '- Entries are **append-only**; corrections are reversing entries, never updates.',
          '- Every posting carries an idempotency key, so a retried request is a no-op rather than a double charge.',
          '- Balances are projections rebuilt from entries — the cache is disposable by design.',
          '- A constraint, not a validation: the sum of a posting is zero at insert time or the transaction fails.',
          '',
          '```sql',
          'CREATE TABLE postings (',
          '  entry_id     bigint      NOT NULL,',
          '  account_id   text        NOT NULL,',
          '  amount_halak integer     NOT NULL, -- smallest unit, never a float',
          '  direction    smallint    NOT NULL CHECK (direction IN (-1, 1))',
          ');',
          '',
          '-- a posting that does not balance cannot exist',
          'CREATE VIEW unbalanced_entries AS',
          'SELECT entry_id FROM postings GROUP BY entry_id HAVING sum(amount_halak * direction) <> 0;',
          '```',
          '',
          '## Results',
          '',
          'The audit that used to take two analysts and a weekend became a query. It survived one storage migration, one datacenter move and a duplicated message storm that turned out to be a non-event because the idempotency keys did their job.',
          '',
          '## Stack',
          '',
          'Go, PostgreSQL 15 with generated columns for projections, gRPC for the internal API, Kafka for downstream consumers.',
        ].join('\n'),
      },
    ],
    fa: [
      {
        title: 'outbox-go',
        slug: 'outbox-go',
        href: 'https://github.com/kianrahmani/outbox-go',
        dates: 'مهر ۱۴۰۴ - اکنون',
        active: true,
        featured: true,
        createdAt: '2026-03-22T08:00:00.000Z',
        image: cover('outbox-go-library'),
        description:
          'یک کتابخانه کوچک Go برای الگوی transactional outbox: رویدادهای دامنه را در همان تراکنش نوشتن منتشر کن و هیچ‌وقت یکی را به قطعی broker واگذار نکن.',
        technologies: ['Go', 'PostgreSQL', 'Kafka', 'OpenTelemetry'],
        links: [
          { type: 'سورس', href: 'https://github.com/kianrahmani/outbox-go', icon: 'github' },
          { type: 'مستندات', href: 'https://outbox-go.example.com', icon: 'docs' },
        ],
        details: [
          '## باگی که این کتابخانه برای نشدنش نوشته شده',
          '',
          'این الگو در هر کدبیزی که کار کرده‌ام پیدا می‌شود: نوشتن در دیتابیس و بعد منتشر کردن در broker. در staging کار می‌کند و در production می‌سوزد، چون فراخوانی دوم پوشش تراکنش اول نیست. یک timeout بروکر کافی است تا دفتر کل بگوید «تسویه شد» و سرویس اعلان بگوید هیچی.',
          '',
          '## چطور کار می‌کند',
          '',
          '۱. رویدادهای دامنه **در همان تراکنش** تغییر وضعیت، در جدول `outbox_events` درج می‌شوند.',
          '۲. یک poller (یا trigger روی `LISTEN` در PostgreSQL) جدول را به Kafka می‌ریزد، با یک شماره ترتیب به ازای هر aggregate؛ پس ترتیب به ازای کلید حفظ می‌شود، نه به ازای پارتیشن.',
          '۳. مصرف‌کننده‌ها بر پایه `(aggregate_id, seq)` حذف تکرای می‌کنند، بنابراین دوباره‌تحویل از نظر ساختاری امن است.',
          '',
          '## آنچه عمداً وجود ندارد',
          '',
          'فریمورک، تزریق وابستگی و کدجنریشن نیست؛ تا دو ستون هم درباره schema نظر نمی‌دهد. ۹۰۰ خط کد است و کل تست‌ها روی یک PostgreSQL واقعی در CI اجرا می‌شوند.',
          '',
          '## اعداد',
          '',
          '| سنجه | مقدار |',
          '| --- | --- |',
          '| ستاره | ۱٬۲۴۰ |',
          '| استفاده‌کننده معرفی‌شده در production | بیش از ۶۰ |',
          '| انتشار رویداد در اوج (یک نود) | ۱۲ هزار بر ثانیه |',
          '| رویداد گم‌شده از 1.0.0 | ۰ |',
          '',
          '## پشته فناوری',
          '',
          'Go 1.23، pgx، confluent-kafka-go، spanهای OpenTelemetry و testcontainers برای تست یکپارچه‌سازی.',
        ].join('\n'),
      },
      {
        title: 'پایپ‌لاین تسویه',
        slug: 'settlement-pipeline',
        href: 'https://zarch.example.com/settlement',
        dates: 'دی ۱۴۰۲ - مهر ۱۴۰۳',
        active: true,
        featured: true,
        createdAt: '2024-11-06T08:00:00.000Z',
        image: cover('settlement-pipeline'),
        description:
          'باتچ تسویه شبانه، بازسازیشده به شکل یک پایپ‌لاین رویدادمحور: پول تقریباً بلادرنگ جابه‌جا می‌شود و مغایرت‌گیری یک کوئری است، نه یک اتاق جنگ.',
        technologies: ['Go', 'Kafka', 'PostgreSQL', 'Kubernetes', 'gRPC', 'ClickHouse'],
        links: [
          { type: 'مستندات', href: 'https://zarch.example.com/settlement/docs', icon: 'docs' },
          { type: 'وب‌سایت', href: 'https://zarch.example.com/settlement', icon: 'website' },
        ],
        details: [
          '## پیش',
          '',
          'تسویه ساعت دو بامداد به شکل یک باتچ اجرا می‌شد: هشت ساعت SQL، تیمی که به نوار پیشرفت نگاه می‌کرد و طرحی برای rollback که معنایش این بود «امروز تسویه نکن». به پذیرنده می‌گفتیم پولت فردا می‌رسد و صادقانه‌ترین پاسخ «شاید پس‌فردا» بود.',
          '',
          '## پس',
          '',
          '- هر برداشت، بازگشت وجه و کارمزد یک رویداد روی topic فشرده‌شده با کلید گروه تسویه است.',
          '- یک مصرف‌کننده حالت‌دار در Go موجودی جاری را در RocksDB نگه می‌دارد و به محض عبور از cutoff، صورتحساب تسویه را می‌فرستد.',
          '- مغایرت‌گیری یک materialized view است که با فایل بانکی join می‌شود؛ یک alert به‌جای یک صفحه‌گسترده و اختلاف‌ها چند دقیقه بعد نام دارند.',
          '- replay یک عملیات درجه‌یک است: یک topic تازه، یک consumer group از صفر و سه ساعت بازسازی حالت به‌جای دو روز.',
          '',
          '## نتیجه',
          '',
          '| سنجه | باتچ | پایپ‌لاین |',
          '| --- | --- | --- |',
          '| تأخیر تسویه | ۱۹ ساعت | ۹۰ ثانیه |',
          '| کشف مغایرت | صبح روز بعد | ۴ دقیقه |',
          '| تیکت پشتیبانی درباره پول | ۳۱۰ در ماه | ۷۴ در ماه |',
          '| پاج در ساعات شب | ۱۱ در ماه | ۲ در ماه |',
          '',
          '## بخش صادقانه',
          '',
          'دو چیز نزدیک بود این را بکشد. اول، یک فایل بانکی خارج از ترتیب که یک پذیرنده را نود دقیقه دو بار تسویه کرد؛ راه‌حل یک idempotency key در سمت سپرده بود، نه مصرف‌کننده باهوش‌تر. دوم، هزینه: مصرف‌کننده حالت‌دار رایگان نیست و ما بیست درصد افزایش زیرساخت خریدیم، قبل از اینکه با حذف خوشه batch آن را پس بگیریم.',
          '',
          '## پشته فناوری',
          '',
          'Go، Kafka با topic فشرده و producer دقیقاً‌یک‌بار، RocksDB، PostgreSQL، ClickHouse برای آنالیتیکس، Kubernetes، Grafana و OpenTelemetry.',
        ].join('\n'),
      },
      {
        title: 'پشته مشاهده‌پذیری سوییچ',
        slug: 'switch-observability-stack',
        href: 'https://hamrahpay.example.com/observability',
        dates: 'آبان ۱۴۰۲ - خرداد ۱۴۰۳',
        active: true,
        featured: true,
        createdAt: '2024-06-10T08:00:00.000Z',
        image: cover('switch-observability'),
        description: 'تریسینگ، متریک RED و SLO در سطح کسب‌وکار برای سوییچ پرداختی که دیباگش با خواندن لاگ از روی شانه یک نفر انجام می‌شد.',
        technologies: ['OpenTelemetry', 'Grafana', 'Prometheus', 'Go', 'Loki'],
        links: [
          { type: 'مستندات', href: 'https://hamrahpay.example.com/observability/docs', icon: 'docs' },
          { type: 'سورس', href: 'https://github.com/kianrahmani/switch-otel', icon: 'github' },
        ],
        details: [
          '## آنچه داشتیم',
          '',
          'داشبوردی از CPU و حافظه، یک نصب ELK که به آن اعتماد نبود، و فرایند on-call که با این سؤال شروع می‌شد «کدام پذیرنده است؟». تأخیر لبه شبکه اندازه گرفته می‌شد، پس نمی‌شد گفت سوییچ ما کند است یا بانک بالادست.',
          '',
          '## آنچه ساختیم',
          '',
          '- **یک trace به ازای هر انتقال**، از gateway تا ریسک، دفتر کل و adapter بانک، با زمان پاسخ سرویس بالادست به‌عنوان attribute صریح روی span.',
          '- **متریک RED به ازای هر صادرکننده و BIN**، تا «کارت‌های بانک X فیلد می‌شوند» روی نمودار دیده شود نه در شایعه.',
          '- **SLO کسب‌وکاری**: ۹۹٫۵ درصد انتقال‌ها زیر ۱٫۵ ثانیه تأیید شوند، اندازه‌گیری سرتاسری، و پاج فقط بر پایه burn rate با دو پنجره ۵ دقیقه و ۱ ساعت.',
          '- **انضباط cardinality**: شناسه پذیرنده روی متریک نمی‌نشیند، فقط روی لاگ؛ با trace id به هم وصل می‌شوند.',
          '',
          '## نتیجه',
          '',
          '| سنجه | پیش | پس |',
          '| --- | --- | --- |',
          '| میانه زمان رسیدن به ریشه | ۴۷ دقیقه | ۶ دقیقه |',
          '| پاج بیرون از ساعت کاری | ۲۳ در ماه | ۷ در ماه |',
          '| اختلاف «بانک کند است» | ۹ در ماه | ۰ (trace می‌گوید کی) |',
          '',
          '## پشته فناوری',
          '',
          'OpenTelemetry Go SDK و collector، Prometheus، Grafana، Loki و Alertmanager. ریاضی SLO در یک فایل recorded-rules است که هر کسی در تیم می‌تواند بخواند.',
        ].join('\n'),
      },
      {
        title: 'سرویس دفتر کل',
        slug: 'ledger-service',
        href: 'https://hamrahpay.example.com/ledger',
        dates: 'بهمن ۱۴۰۰ - مهر ۱۴۰۱',
        active: true,
        featured: false,
        createdAt: '2022-10-05T08:00:00.000Z',
        image: cover('ledger-service'),
        description:
          'دفتر کل دوبل‌انتی که هر انتقال، بازگشت وجه و کارمزد از آن رد می‌شود: فقط-افزودنی، قابل replay و تنها منبع حقیقت برای اینکه چقدر پول نزد ما است.',
        technologies: ['Go', 'PostgreSQL', 'gRPC', 'Kafka'],
        links: [{ type: 'سورس', href: 'https://github.com/kianrahmani/ledger', icon: 'github' }],
        details: [
          '## چرا دوبل‌انتی',
          '',
          'یک ستون `balance` خلاصه داستانی است که کسی آن را ننوشته. وقتی پول بین کیف پول، کارمزد و تسویه چرخید، تیم بیشتر از آنکه فیچر بسازد، وقتش را صرف ریکونسازی موجودی‌ها می‌کرد. دفتر کل قانون را صریح کرد: هر مبلغ از یک حساب می‌آید و در حساب دیگر می‌نشیند و این دو همیشه توافق دارند.',
          '',
          '## قوانینی که سرویس اجرا می‌کند',
          '',
          '- ثبت‌ها **فقط‌افزودنی‌اند**؛ اصلاح به شکل ثبت برگشتی است، نه update.',
          '- هر posting یک idempotency key دارد، پس درخواست دوباره ارسالی no-op است نه دوبار کسر.',
          '- موجودی‌ها projection بازسازی‌شده از ثبت‌ها هستند؛ به همین دلیل کش، طراحی‌شده برای دور ریختن است.',
          '- یک الزام، نه یک اعتبارسنجی: جمع یک posting در زمان درج صفر است، وگرنه تراکنش رد می‌شود.',
          '',
          '## نتیجه',
          '',
          'ممیزی‌ای که دو تحلیلگر و یک آخر هفته می‌برد، تبدیل به یک کوئری شد. این سرویس یک مهاجرت ذخیره‌سازی، یک جابه‌جایی دیتاسنتر و یک طوفان پیام تکراری را دوام آورد؛ آن طوفان به لطف idempotency key اتفاق نیفتاد.',
          '',
          '## پشته فناوری',
          '',
          'Go، PostgreSQL 15 با ستون generated برای projection، gRPC برای API داخلی و Kafka برای مصرف‌کننده‌های پایین‌دست.',
        ].join('\n'),
      },
    ],
  },

  posts: {
    en: [
      {
        title: 'Idempotency is a product decision',
        slug: 'idempotency-is-a-product-decision',
        summary:
          'Retry-safe APIs look like a technical detail until the day a customer is charged twice. What our idempotency contract actually promises.',
        tags: ['api-design', 'payments', 'distributed-systems'],
        published: true,
        createdAt: '2026-05-12T09:00:00.000Z',
        image: cover('idempotency-contract'),
        content: [
          'Every payments API docs page says "use idempotency keys". Very few say what happens when the key is reused with a *different* body, how long the key lives, or what a client should do when the first request timed out but the operation actually succeeded.',
          '',
          "Those are product decisions dressed as infrastructure, and refusing to answer them just moves the ambiguity into someone's integration.",
          '',
          '## Our contract, in full',
          '',
          '- A key is `I-<issuer>-<ulid>` and the client generates it, not us.',
          "- The first request's **response is stored and replayed** byte for byte, so a retry sees the same body, the same status and the same `Location` header.",
          '- Reusing a key with a different request body is a `422`, permanently. It is not our job to guess which of two different operations the caller meant.',
          '- Keys live 24 hours. After that the operation is considered historic and a fresh key is required — a deliberate trade against a table that grows forever.',
          '',
          '```http',
          'POST /v1/transfers HTTP/1.1',
          'Idempotency-Key: I-zarch-01J9XW3F6QK7',
          'Content-Type: application/json',
          '',
          '{ "from": "acct_18", "to": "acct_44", "amount_halak": 12_500_000 }',
          '```',
          '',
          '## The subtle part',
          '',
          'A retry that arrives while the original is still running must not return the stored response — it must wait or return `409`. We keep an in-flight row with a short lease. Without it, a client that retries every two seconds gets a successful-looking response for work that has not happened yet, and that is how a merchant ends up shipping an order that was never paid for.',
          '',
          '## What we learned the hard way',
          '',
          'Our first version scoped keys per endpoint. A transfer retried against a different host in the cluster was treated as new, and one customer was charged twice during a rolling deploy. Scoping keys to the account and storing them in the same database as the ledger is what closed that hole.',
        ].join('\n'),
      },
      {
        title: 'Backpressure: the fix nobody wants to ship',
        slug: 'backpressure-the-fix-nobody-wants',
        summary:
          'Retries amplify outages. Three years of postmortems in payments taught me that the interesting knob is not the retry count — it is the admission rate.',
        tags: ['kafka', 'reliability', 'go'],
        published: true,
        createdAt: '2025-08-25T09:00:00.000Z',
        image: cover('backpressure-admission'),
        content: [
          'When a dependency slows down, every service in the graph keeps accepting work. The queue grows, timeouts fire, clients retry, and the original 200ms latency becomes a three-hour incident. Not because anything crashed — because nothing pushed back.',
          '',
          '## Retries are a gain, and gains compound',
          '',
          'A client retrying three times with a one-second backoff, behind a gateway retrying twice, multiplies traffic by nine the moment the slowest dependency starts timing out. That is the incident.',
          '',
          '```go',
          '// admission control before the queue, not after',
          'if !limiter.Allow() {',
          '  metrics.AdmissionReject.Inc()',
          '  return ErrTooManyRequests // 429, retry-after: 2s',
          '}',
          '```',
          '',
          '## What actually helped',
          '',
          '1. **A load-shedding threshold per consumer.** When lag passes ninety seconds, the consumer stops taking new groups and lets the producer buffer. A visible, boring, documented rejection is better than a hidden, growing backlog.',
          '2. **Retry budgets, not retry counts.** Ten percent of requests may be retries; beyond that, drop. Exponential backoff without a budget is just a slower avalanche.',
          '3. **One place owns the deadline.** A request carries a deadline from the edge; every hop subtracts its own budget and refuses to start work it cannot finish in time.',
          '',
          '## The uncomfortable trade',
          '',
          'Backpressure means telling someone no while the system is still technically up. Product teams hate it, so it needs to be agreed in advance, with a number attached: "we reject up to X% of transfers for ninety seconds instead of degrading all of them". That sentence is in our runbook, and it is the reason the last two incidents ended in four minutes.',
        ].join('\n'),
      },
      {
        title: 'Zero-downtime Postgres migrations, one lock at a time',
        slug: 'zero-downtime-postgres-migrations',
        summary:
          'How to change a table that is serving two thousand transactions a second without a maintenance window — and the four statements that will still stop the world.',
        tags: ['postgresql', 'migrations', 'devops'],
        published: true,
        createdAt: '2024-12-03T09:00:00.000Z',
        updatedAt: '2025-04-20T09:00:00.000Z',
        image: cover('postgres-migrations'),
        content: [
          'A migration does not need to be dangerous. It needs to be sequenced. Every incident I have caused with a schema change came from taking a lock longer than the `statement_timeout` of something else.',
          '',
          '## The rules I run by',
          '',
          '- Add columns as nullable, backfill in batches, only then add the constraint.',
          '- Never `ALTER TABLE ... ADD COLUMN ... DEFAULT <volatile>` on a hot table. On PostgreSQL 11+ a constant default is metadata-only; a function call is not.',
          '- Create indexes with `CONCURRENTLY`, in their own migration, outside a transaction.',
          '- Set `lock_timeout` on the session before any DDL, so a blocked migration gives up instead of queueing an avalanche.',
          '',
          '```sql',
          '-- one: widen, cheap, no rewrite',
          'ALTER TABLE postings ADD COLUMN currency char(3) NULL;',
          '',
          '-- two: batched backfill, 5k rows at a time, with a sleep',
          "UPDATE postings SET currency = 'IRR' WHERE id > $1 AND id <= $2 AND currency IS NULL;",
          '',
          '-- three: validate separately',
          'ALTER TABLE postings VALIDATE CONSTRAINT postings_currency_not_null;',
          '```',
          '',
          '## The four statements that still stop the world',
          '',
          '| Statement | Why it hurts |',
          '| --- | --- |',
          '| `REWRITE`-ing ALTER (`TYPE`, `DROP NOT NULL` after backfill) | full table copy plus exclusive lock |',
          '| `ALTER TABLE ... SET SCHEMA` | rewrites every index name |',
          '| `VACUUM FULL` | exclusive lock, no concurrency |',
          '| `CREATE INDEX` without `CONCURRENTLY` | blocks writes for the whole build |',
          '',
          '## Expand, backfill, contract',
          '',
          'Two deploys per change: the first is additive and both code paths work, the second removes the old column once every writer has moved. Nothing is ever dropped in the same release that stops writing to it.',
          '',
          'The boring conclusion: schema changes are a rollout, and a rollout needs a rollback.',
        ].join('\n'),
      },
      {
        title: 'Notes on writing RFCs that get read',
        slug: 'notes-on-writing-rfcs-that-get-read',
        summary:
          'Two pages, one decision, three named objections. Working notes on the document format that ended most of our architecture arguments.',
        tags: ['architecture', 'communication', 'career'],
        published: false,
        createdAt: '2026-08-15T09:00:00.000Z',
        image: cover('rfc-that-get-read'),
        content: [
          'Draft. The format that has worked for us:',
          '',
          '- **Problem**, four sentences, no solution words allowed.',
          '- **Constraints** — what we are not willing to trade away.',
          '- **Two or three options**, each with its strongest objection named by someone who does not like it.',
          '- **Decision** and **what would change my mind**.',
          '',
          "Two pages maximum; a longer RFC is usually an unfinished one. The objections section does the heavy lifting — once an engineer's concern is written down in their own words, they stop relitigating the decision in Slack.",
          '',
          'Open question: how do we handle the RFCs nobody has read by the time the decision is made?',
        ].join('\n'),
      },
    ],
    fa: [
      {
        title: 'Idempotency یک تصمیم محصولی است',
        slug: 'idempotency-is-a-product-decision',
        summary:
          'API مقاوم در برابر retry تا روزی که مشتری دو بار کسر شود یک جزئیات فنی به نظر می‌رسد. قرارداد idempotency ما دقیقاً چه قولی می‌دهد.',
        tags: ['api-design', 'payments', 'distributed-systems'],
        published: true,
        createdAt: '2026-05-12T09:00:00.000Z',
        image: cover('idempotency-contract'),
        content: [
          'هر صفحه مستندات API پرداخت می‌نویسد «از idempotency key استفاده کنید». خیلی کمند که بگویند اگر کلید دوباره استفاده شد اما body *متفاوت* بود چه می‌شود، کلید چقدر عمر می‌کند، یا کلاینتی که اولین درخواستش timeout شده ولی عملیات در واقع انجام شده باید چه کار کند.',
          '',
          'اینها تصمیم محصولی‌اند که لباس زیرساخت پوشیده‌اند. جواب ندادن به آن‌ها ابهام را به یکپارچه‌سازی مشتری منتقل می‌کند.',
          '',
          '## قرارداد ما، کامل',
          '',
          '- کلید به شکل `I-<issuer>-<ulid>` است و کلاینت آن را می‌سازد، نه ما.',
          '- پاسخ **اولین درخواست ذخیره و بیت‌به‌بیت پخش دوباره می‌شود**؛ پس retry همان body، همان status و همان هدر `Location` را می‌بیند.',
          '- استفاده دوباره کلید با body متفاوت برای همیشه `422` است. حدس زدن اینکه caller کدام از دو عملیات متفاوت را می‌خواسته، وظیفه ما نیست.',
          '- کلید ۲۴ ساعت عمر می‌کند. بعد از آن عملیات تاریخی محسوب می‌شود و کلید تازه لازم است؛ یک معامله آگاهانه با جدولی که برای همیشه بزرگ می‌شود.',
          '',
          '## بخش ظریف کار',
          '',
          'retry که در حالی برسد که درخواست اصلی هنوز در حال اجراست نباید پاسخ ذخیره‌شده را برگرداند؛ باید صبر کند یا `409` بدهد. ما یک ردیف in-flight با lease کوتاه نگه می‌داریم. بدون آن، کلاینتی که هر دو ثانیه retry می‌کند پاسخ موفق‌نما برای کاری می‌گیرد که هنوز انجام نشده — و همین باعث می‌شود یک سفارش پرداخته‌نشده ارسال شود.',
          '',
          '## چیزی که به سختی یاد گرفتیم',
          '',
          'نسخه اول کلیدها را به ازای endpoint محدوده می‌کرد. یک transfer که در نود دیگری از کلاستر retry می‌شد جدید حساب می‌شد و یک مشتری در میانه یک دیپلوی رولینگ دو بار کسر شد. محدوده‌کردن کلید به حساب و ذخیره آن در همان دیتابیس دفتر کل، همان سوراخ را بست.',
        ].join('\n'),
      },
      {
        title: 'Backpressure؛ راه‌حلی که هیچ‌کس نمی‌خواهد منتشر کند',
        slug: 'backpressure-the-fix-nobody-wants',
        summary: 'retry قطعی را بزرگ‌تر می‌کند. سه سال postmortem در پرداخت به من یاد داد پیچ مهم تعداد retry نیست؛ نرخ پذیرش است.',
        tags: ['kafka', 'reliability', 'go'],
        published: true,
        createdAt: '2025-08-25T09:00:00.000Z',
        image: cover('backpressure-admission'),
        content: [
          'وقتی یک وابستگی کند می‌شود، هر سرویس در گراف به پذیرفتن کار ادامه می‌دهد. صف بزرگ می‌شود، timeout فعال می‌شود، کلاینت retry می‌کند و تأخیر دویست‌میلی‌ثانیه‌ای به یک رخداد سه‌ساعته تبدیل می‌شود. نه به خاطر اینکه چیزی crash کرد، به خاطر اینکه چیزی فشار برگشتی وارد نکرد.',
          '',
          '## retry یک تقویت‌کننده است و تقویت‌کننده‌ها جمع می‌شوند',
          '',
          'کلاینتی با سه retry و backoff یک‌ثانیه‌ای، پشت دروازه‌ای با دو retry، درست در لحظه‌ای که کندترین وابستگی شروع به timeout می‌کند، ترافیک را نه برابر می‌کند. همان رخداد است.',
          '',
          '## چه چیزی واقعاً کمک کرد',
          '',
          '۱. **آستانه load shedding برای هر consumer.** وقتی lag از نود ثانیه عبور می‌کند، consumer گروه جدید نمی‌گیرد و producer را به buffer وادار می‌کند. یک رد شدن دیدنی، کسل‌کننده و مستند بهتر از انباشته‌ای پنهان و بزرگ‌تر است.',
          '۲. **بودجه retry نه تعداد retry.** ده درصد درخواست‌ها می‌تواند retry باشد؛ بعد از آن حذف. backoff نمایی بدون بودجه، فقط ریزش کندتر است.',
          '۳. **یک جا مالک deadline است.** درخواست از لبه یک deadline با خود می‌آورد؛ هر پرش بودجه خودش را کم می‌کند و اگر کار را در زمان باقی‌مانده تمام نمی‌کند، شروعش نمی‌کند.',
          '',
          '## معامله ناراحت‌کننده',
          '',
          'Backpressure یعنی در حالی که سیستم از نظر فنی بالاست به کسی نه بگوییم. تیم محصول دوست ندارد، پس باید از پیش با یک عدد توافق شود: «تا نود ثانیه X درصد انتقال‌ها را رد می‌کنیم تا همه‌شان افت نکند». همان جمله در runbook ما است و دلیل اینکه دو رخداد آخر در چهار دقیقه تمام شدند.',
        ].join('\n'),
      },
      {
        title: 'مهاجرت بدون قطعی در PostgreSQL، یک قفل در هر زمان',
        slug: 'zero-downtime-postgres-migrations',
        summary:
          'چگونه ساختار جدولی که ثانیه‌ای دو هزار تراکنش را سرو می‌کند بدون maintenance window عوض کنیم — و چهار دستوری که هنوز جهان را متوقف می‌کنند.',
        tags: ['postgresql', 'migrations', 'devops'],
        published: true,
        createdAt: '2024-12-03T09:00:00.000Z',
        updatedAt: '2025-04-20T09:00:00.000Z',
        image: cover('postgres-migrations'),
        content: [
          'یک مهاجرت لازم نیست خطرناک باشد؛ باید ترتیب‌دار باشد. هر رخدادی که من با تغییر schema ساخته‌ام از این آمده که قفل را بلندتر از `statement_timeout` چیز دیگری نگه داشته‌ام.',
          '',
          '## قوانینی که رعایت می‌کنم',
          '',
          '- ستون جدید را nullable اضافه کن، backfill را دسته‌ای انجام بده و بعد محدودیت را اضافه کن.',
          '- روی جدول شلوغ هرگز `ADD COLUMN ... DEFAULT <volatile>` نکن. در PostgreSQL 11 به بعد مقدار پیش‌فرض ثابت فقط متادیتا است، اما یک فراخوانی تابعی نیست.',
          '- ایندکس را با `CONCURRENTLY` بساز، در مهاجرت مستقل و بیرون از تراکنش.',
          '- پیش از هر DDL روی session مقدار `lock_timeout` بگذار تا مهاجرت قفل‌شده به‌جای صف کردن یک بهمن، تسلیم شود.',
          '',
          '## expand، backfill، contract',
          '',
          'دو دیپلوی برای هر تغییر: اولی افزودنی است و هر دو مسیر کد کار می‌کنند، دومی ستون قدیمی را حذف می‌کند وقتی همه نویسنده‌ها جابه‌جا شده‌اند. هیچ‌چیز در همان ریلیزی که نوشتنش متوقف می‌شود، حذف نمی‌شود.',
          '',
          'نتیجه کسل‌کننده: تغییر schema یک rollout است و rollout به rollback نیاز دارد.',
        ].join('\n'),
      },
      {
        title: 'یادداشت‌هایی درباره نوشتن RFC که خوانده می‌شود',
        slug: 'notes-on-writing-rfcs-that-get-read',
        summary: 'دو صفحه، یک تصمیم و سه ایراد با نام. یادداشت کاری درباره قالبی که بیشتر بحث‌های معماری ما را تمام کرد.',
        tags: ['architecture', 'communication', 'career'],
        published: false,
        createdAt: '2026-08-15T09:00:00.000Z',
        image: cover('rfc-that-get-read'),
        content: [
          'پیش‌نویس. قالبی که برای ما کار کرده:',
          '',
          '- **مسئله**، چهار جمله، بدون اجازه استفاده از کلمات مربوط به راه‌حل.',
          '- **محدودیت‌ها** — آنچه حاضری بابتش معامله نکنی.',
          '- **دو یا سه گزینه**، هرکدام با قوی‌ترین ایرادی که کسی که آن را دوست ندارد نام می‌برد.',
          '- **تصمیم** و **چه چیزی نظرم را عوض می‌کند**.',
          '',
          'حداکثر دو صفحه؛ RFC بلندتر معمولاً RFC ناقص است. بخش ایرادها بار اصلی را به دوش می‌کشد — وقتی نگرانی یک مهندس با کلمات خودش نوشته می‌شود، دیگر تصمیم را در اسلک باز می‌کوبد.',
          '',
          'سؤال باز: با RFCهایی که تا لحظه تصمیم هیچ‌کس نخوانده‌شان چه کنیم؟',
        ].join('\n'),
      },
    ],
  },
};
