import { bullets, cover, portrait, type Persona } from './types';

/**
 * Mina Rahimi — product designer working on interfaces, design systems and motion.
 *
 * Same schema, different discipline: projects read as case studies with research
 * and outcomes, skills are craft skills, and the writing is about users rather
 * than infrastructure.
 */
export const designer: Persona = {
  id: 'designer',
  label: 'Product designer · interfaces, systems & motion',

  profile: {
    en: [
      {
        name: 'Mina',
        fullName: 'Mina Rahimi',
        jobTitle: 'Product Designer · Interfaces & Motion',
        summary:
          'I design interfaces people finish using: research that is affordable, flows that survive a slow connection, and systems engineers actually adopt.',
        description: [
          'Eleven years of product design, seven of them on Persian-speaking users. I started in brand and editorial design, moved into interfaces when a client asked why nobody completed the form I had drawn, and have been designing flows rather than screens ever since.',
          '',
          'Today I lead design at **Havva Health**, where the person on the other side of the screen is often anxious, often on a phone, and rarely reading my labels for the first time. It is a good place to learn humility.',
          '',
          '### How I work',
          '',
          '- Research sized to the decision, not to the conference talk',
          '- Prototypes in the real medium: interaction problems cannot be reviewed in a static frame',
          '- Systems over screens — tokens, component specs and an upgrade path engineers will accept',
          '- Persian typography treated as a design requirement, not a font swap',
          '',
          'I write about interface craft in Persian, teach a typography workshop, and keep a folder of screenshots of bad date pickers.',
        ].join('\n'),
        avatarUrl: portrait('mina-rahimi'),
        tel: '+98 912 777 0239',
        email: 'studio@minarahimi.design',
      },
    ],
    fa: [
      {
        name: 'مینا',
        fullName: 'مینا رحیمی',
        jobTitle: 'طراح محصول · رابط و موشن',
        summary:
          'رابط‌هایی را طراحی می‌کنم که کاربر تا آخر با آن‌ها کار می‌کند: تحقیق به‌اندازه تصمیم، جریان‌هایی که شبکه کند را دوام می‌آورند و سیستمی که مهندسان واقعاً قبولش کنند.',
        description: [
          'یازده سال طراحی محصول، هفت‌تاش روی کاربر فارسی‌زبان. از طراحی برند و سردبیری شروع کردم، وقتی یک مشتری پرسید چرا هیچ‌کس فرمی را که کشیده‌ام تمام نمی‌کند وارد رابط شدم و از آن روز جریان طراحی می‌کنم، نه صفحه.',
          '',
          'الان سرپرست طراحی در **هوا هلث** هستم؛ آن‌طرف صفحه کسی است که معمولاً نگران است، معمولاً با گوشی کار می‌کند و به‌ندرت برچسب‌های من را برای اولین بار می‌خواند. جای خوبی برای یادگیری فروتنی است.',
          '',
          '### چطور کار می‌کنم',
          '',
          '- تحقیق به اندازه تصمیم، نه به اندازه ارائه یک کنفرانس',
          '- نمونه‌ساز در همان رسانه واقعی؛ مسئله تعامل را نمی‌توان در یک فریم ایستا بررسی کرد',
          '- سیستم به‌جای صفحه؛ توکن، مشخصه کامپوننت و مسیر ارتقایی که مهندس بپذیرد',
          '- تایپوگرافی فارسی به‌عنوان یک الزام طراحی، نه عوض‌کردن یک فونت',
          '',
          'درباره مهارت رابط به فارسی می‌نویسم، یک کارگاه تایپوگرافی برگزار می‌کنم و یک پوشه پر از اسکرین‌شات از date pickerهای بد دارم.',
        ].join('\n'),
        avatarUrl: portrait('mina-rahimi'),
        tel: '۰۹۱۲ ۷۷۷ ۰۲۳۹',
        email: 'studio@minarahimi.design',
      },
    ],
  },

  socials: {
    en: [
      { name: 'Website', url: 'https://minarahimi.design', icon: 'website' },
      { name: 'Instagram', url: 'https://instagram.com/mina.draws.ui', icon: 'instagram' },
      { name: 'LinkedIn', url: 'https://www.linkedin.com/in/mina-rahimi-design', icon: 'linkedin' },
      { name: 'Telegram', url: 'https://t.me/mina_ui_notes', icon: 'telegram' },
    ],
    fa: [
      { name: 'وب‌سایت', url: 'https://minarahimi.design', icon: 'website' },
      { name: 'اینستاگرام', url: 'https://instagram.com/mina.draws.ui', icon: 'instagram' },
      { name: 'لینکدین', url: 'https://www.linkedin.com/in/mina-rahimi-design', icon: 'linkedin' },
      { name: 'تلگرام', url: 'https://t.me/mina_ui_notes', icon: 'telegram' },
    ],
  },

  skills: {
    en: [
      { name: 'Figma' },
      { name: 'Design Systems' },
      { name: 'Interaction Design' },
      { name: 'Prototyping' },
      { name: 'User Research' },
      { name: 'Usability Testing' },
      { name: 'Journey Mapping' },
      { name: 'Motion Design' },
      { name: 'After Effects' },
      { name: 'Rive' },
      { name: 'Design Tokens' },
      { name: 'Accessibility' },
      { name: 'Persian Typography' },
      { name: 'Visual Design' },
      { name: 'Brand Identity' },
      { name: 'Framer' },
    ],
    fa: [
      { name: 'فیگما' },
      { name: 'سیستم طراحی' },
      { name: 'طراحی تعامل' },
      { name: 'نمونه‌سازی' },
      { name: 'تحقیق کاربر' },
      { name: 'تست کاربردپذیری' },
      { name: 'نقشه سفر کاربر' },
      { name: 'طراحی موشن' },
      { name: 'After Effects' },
      { name: 'Rive' },
      { name: 'توکن‌های طراحی' },
      { name: 'دسترس‌پذیری' },
      { name: 'تایپوگرافی فارسی' },
      { name: 'طراحی بصری' },
      { name: 'هویت بصری برند' },
      { name: 'Framer' },
    ],
  },

  educations: {
    en: [
      {
        school: 'Interaction Design Foundation',
        degree: 'UX Certification — Research & Evaluation',
        href: 'https://interaction-design.org',
        logoUrl: '',
        start: '2019/01',
        end: '2019/11',
      },
      {
        school: 'University of Art, Tehran',
        degree: 'B.A. Graphic Design — Visual Communication',
        href: 'https://uoart.ac.ir',
        logoUrl: '',
        start: '2014/09',
        end: '2018/07',
      },
    ],
    fa: [
      {
        school: 'مؤسسه طراحی تعامل',
        degree: 'مدرک UX — پژوهش و ارزش‌گذاری',
        href: 'https://interaction-design.org',
        logoUrl: '',
        start: '1397/10',
        end: '1398/08',
      },
      {
        school: 'دانشگاه هنر تهران',
        degree: 'کارشناسی طراحی گرافیک — ارتباط بصری',
        href: 'https://uoart.ac.ir',
        logoUrl: '',
        start: '1393/06',
        end: '1397/04',
      },
    ],
  },

  works: {
    en: [
      {
        company: 'Havva Health',
        title: 'Lead Product Designer',
        location: 'Tehran, Iran · Hybrid',
        href: 'https://havvahealth.example.com',
        logoUrl: '',
        start: '2023/09',
        end: '',
        description: bullets(
          'Own booking, records and the patient app for a platform used by 340 clinics.',
          'Cut abandoned appointments 26% by rebuilding the booking flow around the question patients actually ask: "can I see a doctor today?"',
          'Run research: five sessions a week, every session recorded, every finding in one board engineers can read.',
          'Grew the design system to 120 components and hired the second designer to keep me honest.'
        ),
      },
      {
        company: 'Golbang Commerce',
        title: 'Senior Product Designer',
        location: 'Tehran, Iran',
        href: 'https://golbang.example.com',
        logoUrl: '',
        start: '2021/04',
        end: '2023/08',
        description: bullets(
          'Redesigned checkout and the seller back office for the two highest-traffic surfaces.',
          'Built the first token library shared with front-end; contrast failures in QA dropped to near zero.',
          'Ran the accessibility programme: 41 issues closed, and the WCAG checklist became part of design review.'
        ),
      },
      {
        company: 'Studio Nor',
        title: 'UX Designer',
        location: 'Tehran, Iran',
        href: 'https://studionor.example.com',
        logoUrl: '',
        start: '2019/02',
        end: '2021/03',
        description: bullets(
          'Nineteen client projects: banking apps, two government forms, one museum kiosk.',
          'Introduced usability testing to the studio; it survived one CFO and is still running.'
        ),
      },
      {
        company: 'Freelance',
        title: 'Graphic & Brand Designer',
        location: 'Remote',
        href: '',
        logoUrl: '',
        start: '2016/09',
        end: '2019/01',
        description: bullets(
          'Identity, packaging and editorial work for twelve small businesses.',
          'Learned that a beautiful system nobody maintains is a beautiful problem.'
        ),
      },
    ],
    fa: [
      {
        company: 'هوا هلث',
        title: 'سرپرست طراحی محصول',
        location: 'تهران، ایران · هیبرید',
        href: 'https://havvahealth.example.com',
        logoUrl: '',
        start: '1402/06',
        end: '',
        description: bullets(
          'مالکیت نوبت‌گیری، پرونده و اپ بیمار در پلتفرمی که ۳۴۰ کلینیک از آن استفاده می‌کنند.',
          'کاهش ۲۶ درصدی قرارهای رهاشده با بازسازی جریان رزرو حول همان سؤالی که بیمار واقعاً می‌پرسد: «امروز می‌توانم دکتر ببینم؟»',
          'گردش هفتگی تحقیق: پنج جلسه در هفته، ضبط همه جلسات و همه یافته‌ها در یک بورد مشترک که مهندسان می‌توانند بخوانند.',
          'رساندن سیستم طراحی به ۱۲۰ کامپوننت و استخدام طراح دوم، برای اینکه کسی جلوی سلیقه خودم را بگیرد.'
        ),
      },
      {
        company: 'گل‌بانگ',
        title: 'طراح محصول ارشد',
        location: 'تهران، ایران',
        href: 'https://golbang.example.com',
        logoUrl: '',
        start: '1400/02',
        end: '1402/05',
        description: bullets(
          'بازطراحی پرداخت و پنل فروشنده؛ دو پربازدیدترین بخش سایت.',
          'ساخت نخستین کتابخانه توکن مشترک با تیم فرانت‌اند؛ خطاهای کنتراست در QA تقریباً صفر شد.',
          'راه‌اندازی برنامه دسترس‌پذیری: بستن ۴۱ مورد و تبدیل چک‌لیست WCAG به بخشی از بازبینی طراحی.'
        ),
      },
      {
        company: 'استودیو نور',
        title: 'طراح UX',
        location: 'تهران، ایران',
        href: 'https://studionor.example.com',
        logoUrl: '',
        start: '1397/11',
        end: '1400/01',
        description: bullets(
          'نوزده پروژه مشتری: اپ بانک، دو فرم دولتی و یک کیوسک موزه.',
          'معرفی تست کاربردپذیری به استودیو؛ از یک مدیر مالی جان سالم به در برد و هنوز اجرا می‌شود.'
        ),
      },
      {
        company: 'فریلنس',
        title: 'طراح گرافیک و هویت بصری',
        location: 'دورکاری',
        href: '',
        logoUrl: '',
        start: '1395/06',
        end: '1397/10',
        description: bullets(
          'هویت، بسته‌بندی و کار سردبیری برای دوازده کسب‌وکار کوچک.',
          'یاد گرفتم سیستمی که هیچ‌کس نگهش ندارد، فقط یک مشکل زیباست.'
        ),
      },
    ],
  },

  projects: {
    en: [
      {
        title: 'Sepidar — Persian Numeral Set',
        slug: 'sepidar-persian-numerals',
        href: 'https://sepidar.example.com',
        dates: 'September 2025 - January 2026',
        active: true,
        featured: true,
        createdAt: '2026-01-20T09:00:00.000Z',
        image: cover('sepidar-persian-numerals'),
        description:
          'A numeral and punctuation specimen for Persian interfaces: tabular Persian digits, correct separators, and the tests that prove a receipt aligns in both directions.',
        technologies: ['Figma', 'Glyphs', 'CSS', 'OpenType'],
        links: [
          { type: 'Website', href: 'https://sepidar.example.com', icon: 'website' },
          { type: 'Docs', href: 'https://sepidar.example.com/specimen', icon: 'docs' },
        ],
        details: [
          '## The problem',
          '',
          'Ask a Persian interface to show a table of prices and it will fail in one of three ways: proportional digits that shimmer as rows reorder, Latin digits pasted into Persian sentences, or a separator nobody can agree on. None of them is a font problem. All of them are a specification problem.',
          '',
          '## What this is',
          '',
          'Sepidar is a specimen and a rule set, not a typeface. It defines:',
          '',
          '- **Tabular Persian digits** with a fixed advance width, so invoice columns align.',
          '- **Separators** — thousands as a thin space, decimals as a Arabic decimal separator, and the rule for when a number stays Latin (tracking codes, URLs, phone numbers).',
          '- **Mixed-direction lines** — how an amount next to a Persian label behaves when the whole page is RTL.',
          '',
          '## The unglamorous part',
          '',
          'I wrote the tests before the specimen. A Playwright pass renders the same receipt in both directions at three viewport widths and diffs the column edges; a change that breaks alignment fails, which is the only way a numbering rule survives contact with a product team.',
          '',
          '```css',
          '.amount {',
          '  font-feature-settings: "tnum" 1;',
          '  font-variant-numeric: tabular-nums;',
          '  direction: rtl;',
          '  unicode-bidi: isolate;',
          '}',
          '```',
          '',
          '## Where it is used',
          '',
          'Two products at Havva, the invoice template in a self-hosted billing tool, and a Persian design-systems course that uses the specimen as its typography exercise.',
          '',
          '## Stack',
          '',
          'Figma, Glyphs for metrics, OpenType features, CSS logical properties, Playwright visual tests.',
        ].join('\n'),
      },
      {
        title: 'Havva Booking Flow',
        slug: 'havva-booking-flow',
        href: 'https://havvahealth.example.com/booking',
        dates: 'January 2024 - September 2024',
        active: true,
        featured: true,
        createdAt: '2024-10-05T09:00:00.000Z',
        image: cover('havva-booking-flow'),
        description:
          'Rebuilding a medical appointment flow around the one question patients actually ask: can I see a doctor today? Abandoned bookings down 26%.',
        technologies: ['Figma', 'User Research', 'Usability Testing', 'Design Tokens', 'Rive'],
        links: [
          { type: 'Website', href: 'https://havvahealth.example.com/booking', icon: 'website' },
          { type: 'Video', href: 'https://havvahealth.example.com/booking/walkthrough', icon: 'video' },
        ],
        details: [
          '## What we had',
          '',
          'A five-step flow that started with "select a specialty". Patients do not think in specialties; they think in symptoms, availability and money. Twenty-eight percent of sessions started and never finished, and the analytics could tell me where, not why.',
          '',
          '## Research',
          '',
          '- Twelve moderated sessions in clinics, because the people booking appointments for elderly relatives were not the people our personas described.',
          '- A diary study with nineteen patients over two weeks; "urgent" turned up in four different meanings.',
          '- Support transcripts from six months, sorted by what the user said first rather than by ticket category.',
          '',
          'The finding that reframed everything: users read a date as an answer, not as a field. A calendar open on an empty month is a question with no way out.',
          '',
          '## The redesign',
          '',
          '- **Entry point becomes a question**: "Do you need a doctor today?" branches into same-day availability, this week, or a specific doctor.',
          '- **Time is the primary axis**; specialty is a filter, not a gate.',
          '- **Price and insurance appear before the confirm button**, not after it. This was the second-largest drop-off.',
          '- **One motion, one purpose**: the slot selection animates into the summary so the user never wonders whether the tap registered.',
          '',
          '## Results',
          '',
          '| Measure | Before | After |',
          '| --- | --- | --- |',
          '| Abandoned bookings | 28% | 2% |',
          '| Median time to book | 3 min 40 s | 1 min 10 s |',
          '| Task success (testing, n=15) | 61% | 93% |',
          '| SUS score | 62 | 84 |',
          '| "How do I book" support tickets | 410/mo | 96/mo |',
          '',
          '## What I would do differently',
          '',
          'I would test with the caregivers, not the patients. The person booking for a parent with dementia is the real user of this flow, and we found that in month three of a project that took eight.',
          '',
          '## Stack',
          '',
          'Figma for the system and specs, Maze for unmoderated tests, Rive for the confirmation motion, and tokens shared with the front-end library.',
        ].join('\n'),
      },
      {
        title: 'Nikan Banking Onboarding',
        slug: 'nikan-banking-onboarding',
        href: 'https://nikan.example.com/onboarding',
        dates: 'August 2023 - March 2024',
        active: true,
        featured: true,
        createdAt: '2024-04-12T09:00:00.000Z',
        image: cover('nikan-onboarding'),
        description:
          'Account opening in nine screens instead of twenty-three, with a compliance team in the room for every one of them. Activation up 19%, drop-off at identity verification down by half.',
        technologies: ['Figma', 'Prototyping', 'Usability Testing', 'Motion Design'],
        links: [{ type: 'Video', href: 'https://nikan.example.com/onboarding/film', icon: 'video' }],
        details: [
          '## The constraint',
          '',
          'Regulation decided most of this flow: identity proof, consent text, a cooling-off period, and a screenshot of everything. The interesting design work was not whether to include those steps but what the user is told while waiting for them.',
          '',
          '## What changed',
          '',
          '- **Progress named in the user\'s words.** Nine steps become three: "prove who you are", "choose the account", "agree and finish". The compliance steps stayed, nested inside.',
          '- **Everything resumable.** A session that dies at a camera permission comes back at the same field, not at the start. This was worth eleven percentage points on its own.',
          '- **Camera and OCR as a courtesy, not a requirement.** Every capture screen has a manual path that is exactly as prominent as the automatic one.',
          '- **One explanation surface.** Errors, waiting states and legal text all render in the same component, so the tone never changes mid-flow.',
          '',
          '## Testing',
          '',
          'Twenty-two unmoderated sessions across three cities, plus five in a branch with a staff member present — the population that actually struggles with digital onboarding is not the population that downloads the app.',
          '',
          '## Results',
          '',
          '| Measure | Before | After |',
          '| --- | --- | --- |',
          '| Completed applications | 47% | 71% |',
          '| Identity verification drop-off | 34% | 17% |',
          '| Activation within 24 hours | 52% | 71% |',
          '| Branch visits for help | 1,180/mo | 620/mo |',
          '',
          '## Stack',
          '',
          'Figma and FigJam for research synthesis, ProtoPie for the camera flow, After Effects for the motion spec the engineers implemented frame by frame.',
        ].join('\n'),
      },
      {
        title: 'Golbang Design System',
        slug: 'golbang-design-system',
        href: 'https://golbang.example.com/system',
        dates: 'March 2022 - June 2023',
        active: true,
        featured: false,
        createdAt: '2023-07-01T09:00:00.000Z',
        image: cover('golbang-design-system'),
        description:
          'The design system I co-built with one front-end engineer: tokens, 64 components, and the contribution ritual that made teams actually use it.',
        technologies: ['Figma', 'Design Tokens', 'Storybook', 'Accessibility', 'Variables'],
        links: [
          { type: 'Docs', href: 'https://golbang.example.com/system/docs', icon: 'docs' },
          { type: 'Website', href: 'https://golbang.example.com/system', icon: 'website' },
        ],
        details: [
          '## Where it started',
          '',
          'Four shades of the same brand green, eleven button variants and a checkout where the error style changed depending on which team shipped it. Nobody was wrong; nobody was talking.',
          '',
          '## What we did',
          '',
          '- **Named the decisions, not the colours.** `success-subtle` over `green-300`, so a rebrand is a rename and a component never has to change.',
          '- **Wrote the spec, not just the drawing.** Every component page carries states, RTL behaviour, keyboard contract, contrast pairs and "do not use for" — the last one does the most work.',
          '- **Kept the Figma variables and the code tokens generated from one file.** Drift became impossible rather than discouraged.',
          '- **Made contributing normal.** One open slot in every sprint, a template for requests, and a public adoption table.',
          '',
          '## The part that was actually design',
          '',
          'Convincing people to stop drawing new buttons. The answer was not governance, it was speed: once a component request took two days instead of two weeks, the workaround culture went away on its own.',
          '',
          '## Results',
          '',
          '| Measure | Before | After |',
          '| --- | --- | --- |',
          '| Unique button styles in production | 11 | 4 |',
          '| New screens built from system components | 38% | 89% |',
          '| Contrast defects logged in QA | 24/mo | 3/mo |',
          '',
          '## Stack',
          '',
          'Figma variables, Style Dictionary, Storybook, Tokens Studio, and a weekly fifteen-minute design-engineering standup that solved more than any document did.',
        ].join('\n'),
      },
    ],
    fa: [
      {
        title: 'سپیدار — مجموعه ارقام فارسی',
        slug: 'sepidar-persian-numerals',
        href: 'https://sepidar.example.com',
        dates: 'شهریور ۱۴۰۴ - دی ۱۴۰۵',
        active: true,
        featured: true,
        createdAt: '2026-01-20T09:00:00.000Z',
        image: cover('sepidar-persian-numerals'),
        description:
          'یک نمونه‌حرف و مجموعه قاعده برای ارقام در رابط فارسی: ارقام فارسی tabular، جداکننده درست و تست‌هایی که ثابت می‌کنند یک فاکتور در هر دو جهت راست‌به‌چپ و چپ‌به‌راست تراز می‌ماند.',
        technologies: ['Figma', 'Glyphs', 'CSS', 'OpenType'],
        links: [
          { type: 'وب‌سایت', href: 'https://sepidar.example.com', icon: 'website' },
          { type: 'مستندات', href: 'https://sepidar.example.com/specimen', icon: 'docs' },
        ],
        details: [
          '## مسئله',
          '',
          'از یک رابط فارسی بخواهید جدول قیمت نشان دهد، به یکی از سه روش شکست می‌خورد: ارقام proportional که با هر جابه‌جایی ردیف می‌لرزند، ارقام لاتین چسبانده‌شده در جمله فارسی، یا جداکننده‌ای که هیچ‌کس درباره‌اش توافق ندارد. هیچ‌کدام مسئله فونت نیست؛ همه مسئله فقدان یک مشخصه‌اند.',
          '',
          '## این چیست',
          '',
          'سپیدار یک نمونه‌حرف و مجموعه قاعده است، نه یک تایپ‌فیس. این‌ها را تعریف می‌کند:',
          '',
          '- **ارقام فارسی tabular** با عرض ثابت، تا ستون‌های فاکتور راست بایستند.',
          '- **جداکننده‌ها** — هزارگان با فاصله نازک، اعشار با جداکننده درست، و قاعده اینکه کجا عدد لاتین می‌ماند (کد رهگیری، نشانی وب، شماره تلفن).',
          '- **خط‌های با جهت قاطی** — مبلغی که کنار برچسب فارسی نشسته، وقتی کل صفحه RTL است چه رفتاری دارد.',
          '',
          '## بخش کسل‌کننده کار',
          '',
          'من تست‌ها را قبل از نمونه‌حرف نوشتم. یک پاس Playwright همان فاکتور را در دو جهت و سه عرض ویوپورت رندر و لبه ستون‌ها را مقایسه می‌کند؛ تغییری که تراز را خراب کند رد می‌شود. تنها راهی که یک قاعده شماره‌گذاری با یک تیم محصول برخورد می‌کند و زنده می‌ماند، همین است.',
          '',
          '## کجا استفاده می‌شود',
          '',
          'دو محصول در هوا، قالب فاکتور در یک ابزار صورتحساب خودمیزبان، و یک دوره سیستم طراحی فارسی که نمونه‌حرف را به‌عنوان تمرین تایپوگرافی‌اش استفاده می‌کند.',
          '',
          '## پشته ابزار',
          '',
          'Figma، Glyphs برای متریک، فیچرهای OpenType، خاصیت‌های منطقی CSS و تست بصری Playwright.',
        ].join('\n'),
      },
      {
        title: 'جریان نوبت‌گیری هوا',
        slug: 'havva-booking-flow',
        href: 'https://havvahealth.example.com/booking',
        dates: 'دی ۱۴۰۲ - شهریور ۱۴۰۳',
        active: true,
        featured: true,
        createdAt: '2024-10-05T09:00:00.000Z',
        image: cover('havva-booking-flow'),
        description: 'بازسازی جریان وقت پزشکی حول همان سؤالی که بیمار واقعاً می‌پرسد: امروز می‌توانم دکتر ببینم؟ قرارهای رهاشده ۲۶ درصد کمتر.',
        technologies: ['Figma', 'تحقیق کاربر', 'تست کاربردپذیری', 'Design Tokens', 'Rive'],
        links: [
          { type: 'وب‌سایت', href: 'https://havvahealth.example.com/booking', icon: 'website' },
          { type: 'ویدیو', href: 'https://havvahealth.example.com/booking/walkthrough', icon: 'video' },
        ],
        details: [
          '## آنچه داشتیم',
          '',
          'جریانی پنج‌مرحله‌ای که با «تخصص را انتخاب کنید» شروع می‌شد. بیمار تخصص را این‌طور انتخاب نمی‌کند؛ علامت، زمان خالی و پول را می‌بیند. بیست و هشت درصد نشست‌ها شروع می‌شدند و تمام نمی‌شدند و آنالیتیکس فقط می‌گفت کجا، نه چرا.',
          '',
          '## پژوهش',
          '',
          '- دوازده جلسه همراه با کاربر، داخل خود کلینیک؛ چون کسانی که برای والد مسن وقت می‌گرفتند با پرسونای ما نمی‌خواندند.',
          '- یک مطالعه ثبت روزانه با نوزده بیمار در دو هفته؛ «فوری» در چهار معنای متفاوت ظاهر شد.',
          '- متن گفت‌وگوهای پشتیبانی شش ماه، مرتب‌شده بر پایه نخستین جمله کاربر نه دسته تیکت.',
          '',
          'یافته‌ای که همه‌چیز را عوض کرد: کاربر تاریخ را پاسخ می‌خواند، نه یک فیلد. تقویمی که روی یک ماه خالی باز شود، سؤالی است راه خروج ندارد.',
          '',
          '## بازطراحی',
          '',
          '- **ورود با یک سؤال**: «امروز دکتر لازم دارید؟» به سه شاخه می‌شکافد: همان روز، این هفته، یا یک دکتر مشخص.',
          '- **زمان محور اصلی است**؛ تخصص فیلتر است، نه دروازه.',
          '- **قیمت و بیمه پیش از دکمه تأیید دیده می‌شوند**، نه بعد از آن. این دومین دلیل بزرگ رها کردن بود.',
          '- **یک موشن با یک هدف**: انتخاب وقت به داخل خلاصه می‌رود، تا کاربر لحظه‌ای شک نکند که لمسش ثبت شده است.',
          '',
          '## نتیجه',
          '',
          '| سنجه | پیش | پس |',
          '| --- | --- | --- |',
          '| قرارهای رهاشده | ۲۸٪ | ۲٪ |',
          '| میانه زمان نوبت گرفتن | ۳ دقیقه و ۴۰ ثانیه | ۱ دقیقه و ۱۰ ثانیه |',
          '| موفقیت تسک (تست، n=۱۵) | ۶۱٪ | ۹۳٪ |',
          '| امتیاز SUS | ۶۲ | ۸۴ |',
          '| تیکت «چطور نوبت بگیرم» | ۴۱۰ در ماه | ۹۶ در ماه |',
          '',
          '## آنچه عوض می‌کنم',
          '',
          'با همراهان بیمار تست می‌کردم، نه خود بیمار. کسی که برای پدر مبتلا به آلزایمر وقت می‌گیرد کاربر واقعی این جریان است و ما این را در ماه سوم یک پروژه هشت‌ماهه فهمیدیم.',
          '',
          '## پشته ابزار',
          '',
          'Figma برای سیستم و مشخصه‌ها، Maze برای تست بدون همراه، Rive برای موشن تأیید و توکن‌های مشترک با کتابخانه فرانت‌اند.',
        ].join('\n'),
      },
      {
        title: 'راه‌اندازی حساب نیکان',
        slug: 'nikan-banking-onboarding',
        href: 'https://nikan.example.com/onboarding',
        dates: 'مرداد ۱۴۰۲ - اسفند ۱۴۰۲',
        active: true,
        featured: true,
        createdAt: '2024-04-12T09:00:00.000Z',
        image: cover('nikan-onboarding'),
        description:
          'باز کردن حساب در نه صفحه به‌جای بیست و سه صفحه، با تیم انطباق در اتاق هر تصمیم. فعال‌سازی ۱۹ درصد بالاتر و رها کردن در احراز هویت نصف.',
        technologies: ['Figma', 'نمونه‌سازی', 'تست کاربردپذیری', 'طراحی موشن'],
        links: [{ type: 'ویدیو', href: 'https://nikan.example.com/onboarding/film', icon: 'video' }],
        details: [
          '## محدودیت',
          '',
          'قانون بیشتر این جریان را تعیین می‌کرد: اثبات هویت، متن رضایت، دوره انصراف و یک اسکرین‌شات از همه‌چیز. کار طراحی، اینکه این مرحله‌ها باشند یا نباشند نبود؛ اینکه در انتظار آن‌ها به کاربر چه گفته می‌شود بود.',
          '',
          '## چه چیزی عوض شد',
          '',
          '- **پیشرفت به زبان کاربر.** نه مرحله می‌شود سه: «هویتت را ثابت کن»، «حساب را انتخاب کن»، «تأیید و تمام». مرحله‌های قانونی سر جایشان، تودرتو.',
          '- **همه‌چیز قابل ادامه.** نشستی که روی اجازه دوربین می‌میرد، از همان فیلد برمی‌گردد نه از اول. همین یک چیز یازده درصد ارزش داشت.',
          '- **دوربین و OCR مهمان‌نوازی است، نه اجبار.** روی هر صفحه گرفتن تصویر، مسیر دستی هم‌اندازه خودکار برجسته است.',
          '- **یک سطح توضیح.** خطا، حالت انتظار و متن حقوقی هر سه از یک کامپوننت رندر می‌شوند، پس لحن وسط جریان عوض نمی‌شود.',
          '',
          '## تست',
          '',
          'بیست و دو جلسه بدون همراه در سه شهر، به‌علاوه پنج جلسه در شعبه با حضور کارمند؛ بخشی که واقعاً با ورود دیجیتال مشکل دارد، همان بخشی نیست که اپ را دانلود می‌کند.',
          '',
          '## نتیجه',
          '',
          '| سنجه | پیش | پس |',
          '| --- | --- | --- |',
          '| درخواست‌های کامل‌شده | ۴۷٪ | ۷۱٪ |',
          '| رها کردن در احراز هویت | ۳۴٪ | ۱۷٪ |',
          '| فعال‌سازی در ۲۴ ساعت | ۵۲٪ | ۷۱٪ |',
          '| مراجعه حضوری برای کمک | ۱٬۱۸۰ در ماه | ۶۲۰ در ماه |',
          '',
          '## پشته ابزار',
          '',
          'Figma و FigJam برای سنتز پژوهش، ProtoPie برای جریان دوربین و After Effects برای مشخصه موشنی که مهندسان فریم‌به‌فریم پیاده کردند.',
        ].join('\n'),
      },
      {
        title: 'سیستم طراحی گل‌بانگ',
        slug: 'golbang-design-system',
        href: 'https://golbang.example.com/system',
        dates: 'اسفند ۱۴۰۰ - تیر ۱۴۰۲',
        active: true,
        featured: false,
        createdAt: '2023-07-01T09:00:00.000Z',
        image: cover('golbang-design-system'),
        description: 'سیستم طراحی‌ای که با یک مهندس فرانت‌اند دو نفره ساختیم: توکن، ۶۴ کامپوننت و آیین مشارکتی که تیم‌ها واقعاً از آن استفاده کردند.',
        technologies: ['Figma', 'Design Tokens', 'Storybook', 'دسترس‌پذیری', 'Variables'],
        links: [
          { type: 'مستندات', href: 'https://golbang.example.com/system/docs', icon: 'docs' },
          { type: 'وب‌سایت', href: 'https://golbang.example.com/system', icon: 'website' },
        ],
        details: [
          '## از کجا شروع شد',
          '',
          'چهار طیف از یک سبز برند، یازده واریانت دکمه و پرداختی که استایل خطایش بستگی به تیمی داشت که آن را منتشر کرده بود. هیچ‌کس مقصر نبود؛ هیچ‌کس با هم حرف نمی‌زد.',
          '',
          '## چه کردیم',
          '',
          '- **نام به تصمیم دادیم، نه به رنگ.** `success-subtle` به‌جای `green-300`، پس تغییر برند فقط یک نام‌گذاری است و کامپوننت لازم نیست عوض شود.',
          '- **مشخصه نوشتیم، نه فقط نقشه.** هر صفحه کامپوننت حالت‌ها، رفتار RTL، قرارداد صفحه‌کلید، جفت‌های کنتراست و «برای این کار استفاده نشود» را دارد؛ آخری بیشترین کار را می‌کند.',
          '- **متغیرهای فیگما و توکن‌های کد را از یک فایل تولید کردیم.** واگرایی ناممکن شد، نه فقط بی‌تشویق.',
          '- **مشارکت را عادی کردیم.** یک جای باز در هر اسپرینت، یک قالب برای درخواست و یک جدول آشکار پذیرش.',
          '',
          '## بخشی که واقعاً طراحی بود',
          '',
          'قانع کردن آدم‌ها به نکشیدن دکمه جدید. پاسخ حاکمیت نبود، سرعت بود: وقتی درخواست یک کامپوننت دو روز طول کشید به‌جای دو هفته، فرهنگ دورزدن خودش رفت.',
          '',
          '## نتیجه',
          '',
          '| سنجه | پیش | پس |',
          '| --- | --- | --- |',
          '| استایل دکمه منحصربه‌فرد در production | ۱۱ | ۴ |',
          '| صفحه تازه ساخته‌شده با کامپوننت سیستم | ۳۸٪ | ۸۹٪ |',
          '| خطای کنتراست ثبت‌شده در QA | ۲۴ در ماه | ۳ در ماه |',
          '',
          '## پشته ابزار',
          '',
          'متغیرهای Figma، Style Dictionary، Storybook، Tokens Studio و یک استندآپ پانزده‌دقیقه‌ای طراحی-مهندسی در هفته که بیشتر از هر سندی کار را حل کرد.',
        ].join('\n'),
      },
    ],
  },

  posts: {
    en: [
      {
        title: 'Persian interface typography is a numbering problem',
        slug: 'persian-interface-typography-numbering',
        summary: 'Fonts get all the attention, and the numbers break the layout. A practical spec for digits, separators and mixed-direction lines.',
        tags: ['typography', 'rtl', 'design'],
        published: true,
        createdAt: '2026-03-05T09:00:00.000Z',
        image: cover('persian-typography-numbers'),
        content: [
          'Every Persian design review I attend argues about typefaces. The layout breaks over digits.',
          '',
          '## Choose the digits, then defend the choice',
          '',
          'Persian text with Latin digits is normal on the modern web and looks like a spreadsheet. Persian digits inside a Latin context look wrong to everyone. Both are defensible; a page that mixes them is not.',
          '',
          'The rule that survived three products: **digits follow the language of the sentence, codes follow the language of the system.** An invoice total is Persian, a tracking number and a phone number stay Latin, because someone has to read them aloud over the phone.',
          '',
          '## Tabular or nothing',
          '',
          '```css',
          '.amount, .quantity {',
          '  font-variant-numeric: tabular-nums;',
          '  unicode-bidi: isolate;',
          '}',
          '```',
          '',
          '`isolate` is the part people forget. Without it, a number next to a Persian label in an RTL table can jump sides when the string is reversed by a translation script.',
          '',
          '## Separators need an owner',
          '',
          'Thousands: thin space or comma. Decimal: Arabic decimal separator or a dot. Pick one pair, write it down, and put it next to the token table where both designers and engineers will hit it. Two teams without a written rule will invent two rules, and the receipt will show both.',
          '',
          '## Test the ugly line',
          '',
          'The line that breaks a Persian layout is the one with three directions in it: a label, an amount and a date. Design that row first. If the component holds, the page holds.',
        ].join('\n'),
      },
      {
        title: 'Handoff is a myth; collaboration is the work',
        slug: 'handoff-is-a-myth',
        summary: 'The most useful thing I ever did for a design system was not a spec. It was a fifteen-minute weekly meeting with one engineer.',
        tags: ['design-systems', 'collaboration', 'figma'],
        published: true,
        createdAt: '2025-05-19T09:00:00.000Z',
        image: cover('handoff-myth'),
        content: [
          'A handoff document is a letter to the past. By the time the file is exported, the decision that mattered is already three days old, and the engineer who needed it has built something reasonable and different.',
          '',
          '## What replaced it',
          '',
          '- **A weekly fifteen-minute design-engineering standup.** Two people, one screen, no agenda, everything that felt wrong last week. It solved more than any documentation did, and it was the cheapest process change I have ever made.',
          '- **Specifications in the component, not beside it.** States, RTL behaviour, keyboard contract and contrast pairs live in the same file the engineer already opens.',
          '- **Naming decided together, once.** `danger-subtle` is a name two people agreed on; a name invented in a Figma file is a name nobody types correctly.',
          '- **An adoption table anyone can read.** The most persuasive design argument in our org was a chart of which teams were on which version.',
          '',
          '## What still needs a document',
          '',
          'Rationale, not inventory. Why a component exists and what it must never become — that survives the tool and the person. Everything else can live in code.',
          '',
          '## The uncomfortable metric',
          '',
          'We started counting how many designs shipped without a new component. Sixty-one percent is a good number; a hundred percent means the system is a museum.',
        ].join('\n'),
      },
      {
        title: 'Research you can afford: five users, one afternoon',
        slug: 'research-you-can-afford',
        summary:
          'A full research programme is rarely the blocker. Here is the smallest study that reliably changes a product decision, and how to run it without permission.',
        tags: ['user-research', 'ux', 'career'],
        published: true,
        createdAt: '2024-08-14T09:00:00.000Z',
        updatedAt: '2024-11-02T09:00:00.000Z',
        image: cover('research-you-can-afford'),
        content: [
          'Teams do not fail to do research because there is no budget. They fail because the version of research they imagine requires a lab, a recruit, a synthesis and a two-week calendar. The minimum viable study is smaller than that.',
          '',
          '## The format I trust',
          '',
          '- **Five users, one task, ninety minutes.** Three find most of the severe problems, the fifth tells you whether the third was a fluke.',
          '- **Recruit from people already trying to do the thing.** Support tickets and half-finished sign-ups are a participant list nobody has to pay.',
          '- **Say nothing during the session.** Not a hint, not a reassurance. The silence is the instrument.',
          '- **Record everything, transcribe nothing.** Two hours later, a clipped highlight reel changes more minds than a report.',
          '',
          '## What to do with the findings',
          '',
          'Three sentences, each with the moment it was observed. Not "users struggled with onboarding"; not "the flow is confusing". "At four minutes, two participants looked for a back button in the header" is falsifiable, and falsifiable is what engineering will act on.',
          '',
          '## The permission problem',
          '',
          'Never ask for permission to talk to users. Ask for the recording afterwards. I have run a dozen studies inside companies with a research budget of zero, and the one that needed approval was the one we should not have done at all.',
        ].join('\n'),
      },
      {
        title: 'What motion is for',
        slug: 'what-motion-is-for',
        summary:
          'Draft notes on interface motion: three jobs it can do, the one it must never do, and how to spec it so engineers implement it instead of approximating it.',
        tags: ['motion', 'design', 'craft'],
        published: false,
        createdAt: '2026-08-02T09:00:00.000Z',
        image: cover('what-motion-is-for'),
        content: [
          'Draft. Working thesis: motion is only justified when it answers a question the user is already asking.',
          '',
          '- **Where did that go?** Continuity — the departing element should be visible in the arriving one.',
          '- **Did my tap do anything?** Feedback, under 120ms, or it reads as lag.',
          '- **What changed?** One property, animated; everything else static.',
          '',
          'The one it must never do: decorate a wait. Every easing curve we added to the loading state at Golbang made the two-second response feel longer, not shorter.',
          '',
          'To finish: the spec format that engineers actually use. Curves as `cubic-bezier`, durations as tokens, and the reduced-motion variant in the same frame — not in a paragraph at the end.',
        ].join('\n'),
      },
    ],
    fa: [
      {
        title: 'تایپوگرافی رابط فارسی یک مسئله شماره‌گذاری است',
        slug: 'persian-interface-typography-numbering',
        summary: 'همه بحث سر فونت است و چیدمان روی ارقام می‌شکند. یک مشخصه عملی برای ارقام، جداکننده‌ها و خط‌های با جهت قاطی.',
        tags: ['typography', 'rtl', 'design'],
        published: true,
        createdAt: '2026-03-05T09:00:00.000Z',
        image: cover('persian-typography-numbers'),
        content: [
          'در هر بازبینی طراحی فارسی که شرکت کرده‌ام بحث سر تایپ‌فیس بوده است. چیدمان اما روی ارقام می‌شکند.',
          '',
          '## رقم را انتخاب کن، بعد از انتخاب دفاع کن',
          '',
          'متن فارسی با رقم لاتین در وب امروز طبیعی است و شبیه صفحه‌گسترده به نظر می‌رسد. رقم فارسی در بافت لاتین هم به همه غلط می‌آید. هر دو قابل دفاع است؛ صفحه‌ای که هر دو را قاطی کند، نه.',
          '',
          'قاعده‌ای که سه محصول را پشت سر گذاشت: **رقم پیرو زبان جمله است، کد پیرو زبان سیستم.** مبلغ فاکتور فارسی است، اما کد رهگیری و شماره تلفن لاتین می‌مانند، چون کسی باید آن‌ها را پشت تلفن بلند بخواند.',
          '',
          '## tabular یا هیچ',
          '',
          'کد را در قالب `font-variant-numeric: tabular-nums` و `unicode-bidi: isolate` بنویسید. `isolate` همان بخشی است که فراموش می‌شود؛ بدون آن، عددی که کنار برچسب فارسی در یک جدول RTL نشسته می‌تواند با یک اسکریپت ترجمه طرفش عوض شود.',
          '',
          '## جداکننده مالک می‌خواهد',
          '',
          'هزارگان: فاصله نازک یا ویرگول. اعشار: جداکننده عربی یا نقطه. یک جفت را انتخاب، بنویس و کنار جدول توکن بگذار؛ جایی که هم طراح و هم مهندس به آن می‌خورند. دو تیم بدون قاعده نوشته‌شده، دو قاعده می‌سازند و فاکتور هر دو را نشان می‌دهد.',
          '',
          '## خط زشت را تست کن',
          '',
          'خطی که چیدمان فارسی را می‌شکند همان است که سه جهت دارد: برچسب، مبلغ و تاریخ. اول همان ردیف را طراحی کن. اگر کامپوننت ایستاد، صفحه می‌ایستد.',
        ].join('\n'),
      },
      {
        title: 'تحویل طرح افسانه است؛ همکاری خودِ کار است',
        slug: 'handoff-is-a-myth',
        summary: 'مفیدترین کاری که برای یک سیستم طراحی کردم سند نبود؛ یک جلسه پانزده‌دقیقه‌ای هفتگی با یک مهندس بود.',
        tags: ['design-systems', 'collaboration', 'figma'],
        published: true,
        createdAt: '2025-05-19T09:00:00.000Z',
        image: cover('handoff-myth'),
        content: [
          'سند تحویل، نامه‌ای است به گذشته. وقتی فایل export می‌شود، تصمیم مهم سه روز عمر دارد و مهندسی که به آن نیاز داشته، چیز معقول و متفاوتی ساخته است.',
          '',
          '## جانشین آن',
          '',
          '- **استندآپ پانزده‌دقیقه‌ای هفتگی طراحی و مهندسی.** دو نفر، یک صفحه، بدون دستور جلسه، درباره همه‌چیزی که هفته گذشته بد به نظر می‌آمد. بیشتر از هر مستندی کار کرد و ارزان‌ترین تغییر فرایند من بود.',
          '- **مشخصه داخل کامپوننت، نه کنارش.** حالت‌ها، رفتار RTL، قرارداد صفحه‌کلید و جفت‌های کنتراست در همان فایلی هستند که مهندس از قبل باز می‌کند.',
          '- **نام‌گذاری، یک‌بار و دونفره.** `danger-subtle` نامی است که دو نفر رویش توافق کرده‌اند؛ نامی که در فایل فیگما تنها ساخته شود، نامی است که کسی درست تایپش نمی‌کند.',
          '- **جدول پذیرشی که همه می‌خوانند.** قانع‌کننده‌ترین استدلال طراحی در سازمان ما نموداری بود که نشان می‌داد کدام تیم روی کدام نسخه است.',
          '',
          '## آنچه هنوز سند می‌خواهد',
          '',
          'دلیل، نه فهرست. چرا یک کامپوننت وجود دارد و هرگز نباید به چه چیزی تبدیل شود — آن از ابزار و از آدم باقی می‌ماند. بقیه در کد می‌تواند زندگی کند.',
          '',
          '## سنجه ناراحت‌کننده',
          '',
          'شروع کردیم به شمردن اینکه چند طراحی بدون کامپوننت تازه منتشر می‌شود. شصت و یک درصد عدد خوبی است؛ صد درصد یعنی سیستم یک موزه است.',
        ].join('\n'),
      },
      {
        title: 'پژوهشی که از پسش برمی‌آیید: پنج کاربر، یک بعدازظهر',
        slug: 'research-you-can-afford',
        summary: 'کمبود بودجه به‌ندرت مانع پژوهش است؛ تصویر بزرگ از آن بازدارنده است. کوچک‌ترین مطالعه‌ای که مطمئناً یک تصمیم محصولی را عوض می‌کند.',
        tags: ['user-research', 'ux', 'career'],
        published: true,
        createdAt: '2024-08-14T09:00:00.000Z',
        updatedAt: '2024-11-02T09:00:00.000Z',
        image: cover('research-you-can-afford'),
        content: [
          'تیم‌ها پژوهش نمی‌کنند چون بودجه نیست؛ پژوهش نمی‌کنند چون تصویری که از آن دارند آزمایشگاه می‌خواهد، جذب شرکت‌کننده، سنتز و دو هفته جا در تقویم. کوچک‌ترین مطالعه قابل‌اتکا کوچک‌تر از آن است.',
          '',
          '## قالبی که به آن اعتماد دارم',
          '',
          '- **پنج کاربر، یک تسک، نود دقیقه.** سه نفر بیشتر مشکلات جدی را بیرون می‌کشند؛ نفر پنجم می‌گوید آن سوم تصادفی بود یا نه.',
          '- **از آدم‌هایی پیدا کن که همین حالا دارند همان کار را انجام می‌دهند.** تیکت پشتیبانی و ثبت‌نام نصفه‌کاره لیست شرکت‌کننده‌ای است که کسی نباید بهایش را بدهد.',
          '- **وسط جلسه هیچ نگو.** نه راهنمایی، نه اطمینان. سکوت، ابزار است.',
          '- **همه را ضبط کن، هیچ‌کدام را پیاده نکن.** دو ساعت بعد، یک ویدیوی کوتاه گلچین‌شده بیشتر از یک گزارش ذهن عوض می‌کند.',
          '',
          '## با یافته‌ها چه کنیم',
          '',
          'سه جمله، هرکدام با لحظه‌ای که در آن مشاهده شده. نه «کاربرها در ورود مشکل داشتند»، نه «جریان گیج‌کننده است». «در دقیقه چهارم، دو شرکت‌کننده دنبال دکمه بازگشت در هدر گشتند» ابطال‌پذیر است و ابطال‌پذیر همان چیزی است که مهندسی رویش اقدام می‌کند.',
          '',
          '## مسئله اجازه',
          '',
          'برای حرف زدن با کاربر هیچ‌وقت اجازه نخواه. بعداً برای اشتراک ضبطش اجازه بخواه. من دوازده مطالعه در شرکت‌هایی با بودجه پژوهش صفر اجرا کرده‌ام و همان‌که نیاز به تأیید داشت، هیچ‌کدام نبود که باید انجامش می‌دادیم.',
        ].join('\n'),
      },
      {
        title: 'موشن برای چیست',
        slug: 'what-motion-is-for',
        summary:
          'یادداشت پیش‌نویس درباره موشن رابط: سه کاری که می‌تواند بکند، کاری که هرگز نباید بکند و چگونه مشخصه‌اش را بنویسیم که مهندس آن را تخمین نزند، عینش کند.',
        tags: ['motion', 'design', 'craft'],
        published: false,
        createdAt: '2026-08-02T09:00:00.000Z',
        image: cover('what-motion-is-for'),
        content: [
          'پیش‌نویس. فرضیه کاری: موشن فقط وقتی توجیه دارد که به سؤالی جواب دهد که کاربر از قبل می‌پرسد.',
          '',
          '- **آن رفت کجا؟** تداوم؛ عنصر خروجی باید در عنصر ورودی دیده شود.',
          '- **لمس من چیزی ثبت کرد؟** بازخورد، زیر ۱۲۰ میلی‌ثانیه، وگرنه کُندی خوانده می‌شود.',
          '- **چه چیزی عوض شد؟** یک property متحرک، بقیه ثابت.',
          '',
          'کاری که هرگز نباید بکند: یک انتظار را تزئین کن. هر منحنی easing که به حالت بارگذاری گل‌بانگ اضافه کردیم، همان دو ثانیه پاسخ را بلندتر نشانش داد، نه کوتاه‌تر.',
          '',
          'برای تمام کردن: قالب مشخصه‌ای که مهندسان واقعاً استفاده می‌کنند. منحنی به شکل `cubic-bezier`، مدت به شکل توکن و نسخه reduced-motion در همان فریم، نه در یک پاراگاف آخر.',
        ].join('\n'),
      },
    ],
  },
};
