import { bullets, cover, portrait, type Persona } from './types';

/**
 * Sara Mirzaei — front-end engineer working on design systems.
 *
 * The reference persona: seven years of browser-side work, one open-source
 * library, and a career history that lines up with the dates on the projects.
 * Everything here is fictional demo content.
 */
export const frontend: Persona = {
  id: 'frontend',
  label: 'Front-end engineer · design systems',

  profile: {
    en: [
      {
        name: 'Sara',
        fullName: 'Sara Mirzaei',
        jobTitle: 'Front-end Engineer · Design Systems',
        summary: 'I build fast, accessible interfaces in React and Next.js — and the design systems that keep them consistent as teams grow.',
        description: [
          'Seven years on the browser side of the wall: product interfaces, design systems, and the tooling that keeps both honest. Most of my work sits where engineering meets design — component APIs, tokens, motion, RTL layouts, and the accessibility checks that decide whether an interface survives contact with real users.',
          '',
          'I lead the front-end guild at **Nova Commerce**, where I own the shared component library used by six product teams. Before that I shipped a Persian-first storefront redesign that halved largest contentful paint and lifted mobile checkout completion by twelve percent.',
          '',
          '### What I care about',
          '',
          '- Semantic HTML and a working keyboard path before any JavaScript',
          '- Performance budgets written down, not wished for',
          '- Design systems with an upgrade story, not just a screenshot',
          '- RTL and Latin layouts generated from one source of truth',
          '',
          'Outside work I write about interface engineering, maintain two small open-source packages, and photograph brutalist buildings in Tehran.',
        ].join('\n'),
        avatarUrl: portrait('sara-mirzaei'),
        tel: '+98 912 555 0148',
        email: 'hello@saramirzaei.dev',
      },
    ],
    fa: [
      {
        name: 'سارا',
        fullName: 'سارا میرزایی',
        jobTitle: 'مهندس فرانت‌اند · سیستم طراحی',
        summary: 'رابط‌های کاربری سریع و در دسترس با React و Next.js می‌سازم؛ و سیستم‌طراحی‌هایی که با بزرگ‌شدن تیم، یکدست باقی می‌مانند.',
        description: [
          'هفت سال در سمت مرورگر دیوار: رابط کاربری محصول، سیستم طراحی و ابزارهایی که هر دو را سالم نگه می‌دارند. بیشتر کار من جایی است که مهندسی به طراحی می‌رسد؛ API کامپوننت، توکن، موشن، چیدمان RTL و بررسی‌های دسترس‌پذیری که مشخص می‌کنند یک رابط با کاربر واقعی دوام می‌آورد یا نه.',
          '',
          'الان «گیلد» فرانت‌اند **Nova Commerce** را رهبری می‌کنم و کتابخانه مشترک کامپوننتی را که شش تیم محصول از آن استفاده می‌کنند، نگه می‌دارم. پیش‌تر بازطراحی ویترین فروشگاه فارسی‌زبان را منتشر کردم که LCP را نصف کرد و تکمیل خرید موبایل را دوازده درصد بالا برد.',
          '',
          '### چیزهایی که برایشان وقت می‌گذارم',
          '',
          '- HTML معنایی و مسیر کار با صفحه‌کلید، پیش از هرگونه JavaScript',
          '- بودجه عملکرد نوشته‌شده، نه آرزوی نوشته‌نشده',
          '- سیستم طراحی با داستان ارتقا، نه فقط یک اسکرین‌شات',
          '- چیدمان RTL و لاتین تولیدشده از یک منبع حقیقت واحد',
          '',
          'خارج از کار، درباره مهندسی رابط می‌نویسم، دو پکیج اوپن‌سورس کوچک را نگه می‌دارم و از ساختمان‌های بروتالیست تهران عکس می‌گیرم.',
        ].join('\n'),
        avatarUrl: portrait('sara-mirzaei'),
        tel: '۰۹۱۲ ۵۵۵ ۰۱۴۸',
        email: 'hello@saramirzaei.dev',
      },
    ],
  },

  socials: {
    en: [
      { name: 'Website', url: 'https://saramirzaei.dev', icon: 'website' },
      { name: 'GitHub', url: 'https://github.com/sara-mirzaei', icon: 'github' },
      { name: 'LinkedIn', url: 'https://www.linkedin.com/in/sara-mirzaei', icon: 'linkedin' },
      { name: 'X', url: 'https://x.com/saramirzaei_ui', icon: 'x' },
      { name: 'Telegram', url: 'https://t.me/saramirzaei_dev', icon: 'telegram' },
    ],
    fa: [
      { name: 'وب‌سایت', url: 'https://saramirzaei.dev', icon: 'website' },
      { name: 'گیت‌هاب', url: 'https://github.com/sara-mirzaei', icon: 'github' },
      { name: 'لینکدین', url: 'https://www.linkedin.com/in/sara-mirzaei', icon: 'linkedin' },
      { name: 'ایکس', url: 'https://x.com/saramirzaei_ui', icon: 'x' },
      { name: 'تلگرام', url: 'https://t.me/saramirzaei_dev', icon: 'telegram' },
    ],
  },

  skills: {
    en: [
      { name: 'TypeScript' },
      { name: 'React' },
      { name: 'Next.js' },
      { name: 'JavaScript' },
      { name: 'HTML & CSS' },
      { name: 'Tailwind CSS' },
      { name: 'shadcn/ui' },
      { name: 'Radix UI' },
      { name: 'Framer Motion' },
      { name: 'Vite' },
      { name: 'Vitest' },
      { name: 'Playwright' },
      { name: 'Storybook' },
      { name: 'Design Tokens' },
      { name: 'Accessibility (WCAG)' },
      { name: 'RTL & i18n' },
    ],
    fa: [
      { name: 'TypeScript' },
      { name: 'React' },
      { name: 'Next.js' },
      { name: 'JavaScript' },
      { name: 'HTML و CSS' },
      { name: 'Tailwind CSS' },
      { name: 'shadcn/ui' },
      { name: 'Radix UI' },
      { name: 'Framer Motion' },
      { name: 'Vite' },
      { name: 'Vitest' },
      { name: 'Playwright' },
      { name: 'Storybook' },
      { name: 'توکن‌های طراحی' },
      { name: 'دسترس‌پذیری (WCAG)' },
      { name: 'RTL و بومی‌سازی' },
    ],
  },

  educations: {
    en: [
      {
        school: 'Sharif University of Technology',
        degree: 'M.Sc. Human-Computer Interaction',
        href: 'https://sharif.edu',
        logoUrl: '',
        start: '2018/09',
        end: '2020/07',
      },
      {
        school: 'University of Tehran',
        degree: 'B.Sc. Computer Science',
        href: 'https://ut.ac.ir',
        logoUrl: '',
        start: '2014/09',
        end: '2018/07',
      },
    ],
    fa: [
      {
        school: 'دانشگاه صنعتی شریف',
        degree: 'کارشناسی ارشد تعامل انسان و کامپیوتر',
        href: 'https://sharif.edu',
        logoUrl: '',
        start: '1397/06',
        end: '1399/04',
      },
      {
        school: 'دانشگاه تهران',
        degree: 'کارشناسی مهندسی کامپیوتر',
        href: 'https://ut.ac.ir',
        logoUrl: '',
        start: '1393/06',
        end: '1397/04',
      },
    ],
  },

  works: {
    en: [
      {
        company: 'Nova Commerce',
        title: 'Lead Front-end Engineer',
        location: 'Tehran, Iran · Hybrid',
        href: 'https://novacommerce.example.com',
        logoUrl: '',
        start: '2024/05',
        end: '',
        description: bullets(
          'Own Prism, the design system behind six product teams and 40+ surfaces.',
          'Cut storefront LCP from 4.1s to 1.9s on a mid-range Android over 3G.',
          'Run the front-end guild: RFCs, weekly upgrade trains, mentoring track for four juniors.',
          'Added visual-regression and accessibility gates in CI; design drift is down 70%.'
        ),
      },
      {
        company: 'Parseh Digital',
        title: 'Senior Front-end Developer',
        location: 'Tehran, Iran',
        href: 'https://parsehdigital.example.com',
        logoUrl: '',
        start: '2022/02',
        end: '2024/04',
        description: bullets(
          'Migrated a jQuery monolith to the Next.js App Router: 96 routes, one shell.',
          'Built the RTL checkout that now carries 1.2M orders a year.',
          'Set up Storybook and the first shared token package; design handoff time halved.'
        ),
      },
      {
        company: 'Studio Mehr',
        title: 'Front-end Developer',
        location: 'Remote',
        href: 'https://studiomehr.example.com',
        logoUrl: '',
        start: '2020/04',
        end: '2022/01',
        description: bullets(
          'Shipped 14 client marketing sites from one Astro template and a CMS layer.',
          'Wrote the accessibility checklist the studio still uses at every handoff.',
          'Pair-designed with two designers — learned to argue in tokens, not pixels.'
        ),
      },
      {
        company: 'Freelance',
        title: 'UI Developer',
        location: 'Remote',
        href: '',
        logoUrl: '',
        start: '2018/09',
        end: '2020/03',
        description: bullets(
          'React dashboards and design handoffs for three European startups.',
          'Learned to scope, quote and ship without a team around me.'
        ),
      },
    ],
    fa: [
      {
        company: 'نووا کامرس',
        title: 'سرپرست تیم فرانت‌اند',
        location: 'تهران، ایران · هیبرید',
        href: 'https://novacommerce.example.com',
        logoUrl: '',
        start: '1403/02',
        end: '',
        description: bullets(
          'مالکیت Prism؛ سیستم طراحی‌ای که پشت شش تیم محصول و بیش از ۴۰ صفحه است.',
          'کاهش LCP ویترین از ۴٫۱ ثانیه به ۱٫۹ ثانیه روی اندروید میان‌رده با شبکه 3G.',
          'راه‌اندازی گیلد فرانت‌اند: RFC، قطار ارتقای هفتگی و منتورینگ چهار نیروی تازه‌کار.',
          'افزودن گیت‌های رگرسیون بصری و دسترس‌پذیری به CI؛ ۷۰٪ کاهش اختلاف طراحی و پیاده‌سازی.'
        ),
      },
      {
        company: 'پارسه دیجیتال',
        title: 'توسعه‌دهنده ارشد فرانت‌اند',
        location: 'تهران، ایران',
        href: 'https://parsehdigital.example.com',
        logoUrl: '',
        start: '1400/11',
        end: '1403/01',
        description: bullets(
          'مهاجرت یک monolith با jQuery به Next.js App Router؛ ۹۶ مسیر در یک پوسته.',
          'ساخت فرایند پرداخت RTL که امروز سالانه ۱٫۲ میلیون سفارش را حمل می‌کند.',
          'راه‌اندازی Storybook و نخستین بسته توکن مشترک؛ نصف شدن زمان تحویل طرح به توسعه.'
        ),
      },
      {
        company: 'استودیو مهر',
        title: 'توسعه‌دهنده فرانت‌اند',
        location: 'دورکاری',
        href: 'https://studiomehr.example.com',
        logoUrl: '',
        start: '1399/01',
        end: '1400/10',
        description: bullets(
          'انتشار ۱۴ سایت معرفی مشتری از یک قالب Astro و یک لایه CMS.',
          'نوشتن چک‌لیست دسترس‌پذیری که استودیو هنوز در هر تحویل استفاده می‌کند.',
          'طراحی دونفره با دو طراح — یاد گرفتم با توکن بحث کنم، نه پیکسل.'
        ),
      },
      {
        company: 'فریلنس',
        title: 'توسعه‌دهنده رابط کاربری',
        location: 'دورکاری',
        href: '',
        logoUrl: '',
        start: '1397/06',
        end: '1398/12',
        description: bullets('داشبورد React و تحویل طرح برای سه استارتاپ اروپایی.', 'یادگیری محدوده‌گذاری، قیمت‌دهی و انتشار بدون حضور یک تیم.'),
      },
    ],
  },

  projects: {
    en: [
      {
        title: 'A11y Lens',
        slug: 'a11y-lens',
        href: 'https://a11ylens.example.com',
        dates: 'January 2026 - May 2026',
        active: true,
        featured: true,
        createdAt: '2026-05-30T10:00:00.000Z',
        image: cover('a11y-lens-devtools'),
        description:
          'A browser extension that audits keyboard traps, focus order and RTL mirroring on any page — built because I kept failing my own design reviews.',
        technologies: ['TypeScript', 'React', 'Chrome Extension API', 'axe-core', 'Vite'],
        links: [
          { type: 'Source', href: 'https://github.com/sara-mirzaei/a11y-lens', icon: 'github' },
          { type: 'Docs', href: 'https://a11ylens.example.com/docs', icon: 'docs' },
        ],
        details: [
          '## Why it exists',
          '',
          'Accessibility reviews at Nova kept finding the same four problems: focus that disappears, icons that are the only label, hit areas under 24px, and arrows that never flipped in RTL. None of them showed up in the automated scan.',
          '',
          'A11y Lens inspects the rendered page instead of the source, so it catches what linters cannot.',
          '',
          '## What it does',
          '',
          '- **Focus map** — overlays the tab order as numbered chips and flags any element that leaves the viewport.',
          '- **Keyboard trap** — detects scrollable regions and dialogs that swallow Tab and Escape.',
          '- **RTL mirror** — diffs the LTR and RTL builds and lists every icon, shadow and transform that did not flip.',
          '- **Label audit** — surfaces controls whose accessible name comes from a placeholder or nothing at all.',
          '',
          'Findings export as JSON, Markdown or a GitHub check run, so the report can gate a pull request instead of becoming another tab.',
          '',
          '## Under the hood',
          '',
          'The auditor is a pure function over an accessibility tree snapshot, which means the whole engine runs in tests without a browser:',
          '',
          '```ts',
          'export function auditFocusOrder(snapshot: A11ySnapshot): Finding[] {',
          '  return snapshot.focusables',
          '    .map((node, index) => ({ node, index, rect: node.clientRect }))',
          '    .filter(({ rect }) => rect.width < 24 || rect.height < 24)',
          '    .map(({ node }) => ({',
          "      rule: 'target-size-minimum',",
          '      node,',
          "      hint: 'expand the hit area to 24x24 CSS pixels',",
          '    }));',
          '}',
          '```',
          '',
          '## Results',
          '',
          '| Measure | Result |',
          '| --- | --- |',
          '| Installations | 4,800 |',
          '| Weekly active auditors | 1,100 |',
          '| Median findings per page | 6 |',
          '| RTL issues caught before QA | 83% |',
          '',
          '## Stack',
          '',
          'TypeScript, React, Chrome Extension Manifest V3, axe-core, Vite, Vitest with a jsdom accessibility tree.',
        ].join('\n'),
      },
      {
        title: 'Nova Design System',
        slug: 'nova-design-system',
        href: 'https://novads.example.com',
        dates: 'June 2024 - September 2025',
        active: true,
        featured: true,
        createdAt: '2025-09-20T08:00:00.000Z',
        image: cover('nova-design-system'),
        description: 'Tokens, 148 components and a contribution model for six product teams — one upgrade train, zero bespoke buttons.',
        technologies: ['React', 'TypeScript', 'Radix UI', 'Tailwind CSS', 'Style Dictionary', 'Storybook'],
        links: [
          { type: 'Website', href: 'https://novads.example.com', icon: 'website' },
          { type: 'Docs', href: 'https://novads.example.com/docs', icon: 'docs' },
          { type: 'Source', href: 'https://github.com/sara-mirzaei/nova-ds', icon: 'github' },
        ],
        details: [
          '## The problem',
          '',
          'Six product teams, three design languages, and a codebase in which every button had an opinion. Feature work took a week; deciding whose button to use took two days.',
          '',
          '## What I built',
          '',
          '- **Tokens first.** Colour, spacing, type and motion compile from one JSON source through Style Dictionary into CSS variables, a Tailwind preset and Figma styles.',
          '- **148 components** on Radix primitives. Each one ships with RTL mirroring, dark mode, and a keyboard contract documented in Storybook.',
          '- **An upgrade train.** Weekly canary releases, codemods for breaking changes, and a deprecation policy that gives teams exactly one release to react.',
          '- **Governance.** A proposal template, an adoption dashboard and weekly office hours replaced the “who owns this component” argument.',
          '',
          '## The part that mattered most',
          '',
          'Contributing had to be boring. A team that needs a component opens a request, gets a slot in the roadmap or writes it against the published component API, and the review is a checklist rather than a taste debate. Adoption reached 71% of surfaces in five months, mostly because saying no was cheap.',
          '',
          '## Results',
          '',
          '| Measure | Before | After |',
          '| --- | --- | --- |',
          '| Median UI build time | 6.4 days | 2.1 days |',
          '| Design QA rounds | 3.1 | 1.2 |',
          '| Off-pattern components | 214 | 26 |',
          '| Bundle cost per page | 184 KB | 96 KB |',
          '',
          '## Stack',
          '',
          'TypeScript, Radix UI, Tailwind CSS, Style Dictionary, Storybook, Playwright visual regression, Changesets.',
        ].join('\n'),
      },
      {
        title: 'Vitrin Storefront Redesign',
        slug: 'vitrin-storefront-redesign',
        href: 'https://vitrin-shop.example.com',
        dates: 'March 2023 - November 2023',
        active: true,
        featured: true,
        createdAt: '2023-12-02T09:00:00.000Z',
        image: cover('vitrin-storefront'),
        description:
          'A Persian-first commerce rebuild: server components, an optimistic cart, and a checkout that still works on a five-year-old Android over 3G.',
        technologies: ['Next.js', 'TypeScript', 'React Server Components', 'Tailwind CSS', 'Zustand', 'Playwright'],
        links: [
          { type: 'Website', href: 'https://vitrin-shop.example.com', icon: 'website' },
          { type: 'Source', href: 'https://github.com/sara-mirzaei/vitrin', icon: 'github' },
        ],
        details: [
          '## The brief',
          '',
          'Seventy-one percent of traffic was mobile, the median device was four years old, and the network was not 4G. The old storefront took eleven seconds to first meaningful paint and lost two of every three carts at the address step.',
          '',
          '## Decisions that moved the numbers',
          '',
          '- **Render on the server, hydrate nothing you cannot see.** Product pages became React Server Components; the client bundle for a category page dropped from 412 KB to 96 KB.',
          '- **Cart state stays local.** An optimistic cart writes to IndexedDB first and reconciles later, so adding an item responds instantly even when the network is slow.',
          '- **Fonts over icons.** The Persian webfont is subset per template and preloaded; the Arabic-shaping fallbacks that used to reflow every line are gone.',
          '- **One input component, RTL-correct.** Steppers, masks and phone inputs were rebuilt once and shared with checkout, support and the seller back office.',
          '',
          '```css',
          '/* Logical properties instead of left/right, so one stylesheet serves both directions */',
          '.cart-line {',
          '  padding-inline: 1rem;',
          '  border-inline-start: 1px solid var(--rule);',
          '}',
          '```',
          '',
          '## Results',
          '',
          '| Metric | Before | After |',
          '| --- | --- | --- |',
          '| LCP (p75, mobile) | 4.1s | 1.9s |',
          '| CLS | 0.31 | 0.04 |',
          '| Checkout completion | 61% | 73% |',
          '| Bounce on product pages | 48% | 33% |',
          '',
          'The performance budget is now a CI gate: any pull request that pushes LCP past 2.5s on the throttled profile fails the check.',
          '',
          '## Stack',
          '',
          'Next.js App Router, React Server Components, TypeScript, Tailwind CSS, Zustand, Playwright, Web Vitals routed to Grafana.',
        ].join('\n'),
      },
      {
        title: 'Persian Date Kit',
        slug: 'persian-date-kit',
        href: 'https://persiandatekit.example.com',
        dates: 'May 2022 - October 2022',
        active: true,
        featured: false,
        createdAt: '2022-10-10T07:00:00.000Z',
        image: cover('persian-date-kit'),
        description: 'A zero-dependency Jalaali date library with Intl-based formatting and RTL-safe React components. Around 40k downloads a week.',
        technologies: ['TypeScript', 'React', 'Intl API', 'Vitest'],
        links: [
          { type: 'Source', href: 'https://github.com/sara-mirzaei/persian-date-kit', icon: 'github' },
          { type: 'Docs', href: 'https://persiandatekit.example.com', icon: 'docs' },
          { type: 'Download', href: 'https://www.npmjs.com/package/persian-date-kit', icon: 'download' },
        ],
        details: [
          '## The problem',
          '',
          'Every Persian project I joined solved dates the same way: a hand-rolled conversion table copy-pasted from a 2012 blog post, off by a day around Nowruz and useless for formatting.',
          '',
          '## Approach',
          '',
          '- **No conversion tables.** The Jalaali calendar is delegated to `Intl.DateTimeFormat` with the `fa-IR-u-ca-persian` extension, so the browser owns the arithmetic.',
          '- **Formatting is locale data, not string templates.** Month names, digits and separators come from `Intl`, so Persian digits never have to be patched in afterwards.',
          '- **Components stay direction-safe.** `DateField`, `DateRangePicker` and `Calendar` render inside a `dir=\"rtl\"` run and flip their own chevrons.',
          '',
          '```ts',
          "import { format } from 'persian-date-kit';",
          '',
          "format('2026-03-21', { locale: 'fa', dateStyle: 'long' });",
          '// ‹۱ فروردین ۱۴۰۵›',
          "format('2026-03-21', { locale: 'en', dateStyle: 'long' });",
          '// ‹March 21, 2026›',
          '```',
          '',
          '## What I learned maintaining it',
          '',
          'Two years of issues taught me that a date library is mostly error handling: invalid input, DST edges, calendars that disagree about a leap year. The API is now explicit about the calendar it returns and it never guesses a timezone.',
          '',
          '## Stack',
          '',
          'TypeScript, Intl, React 19, Vitest with 100% branch coverage, Size-limit at 4.2 KB gzipped.',
        ].join('\n'),
      },
    ],
    fa: [
      {
        title: 'A11y Lens',
        slug: 'a11y-lens',
        href: 'https://a11ylens.example.com',
        dates: 'دی ۱۴۰۴ - اردیبهشت ۱۴۰۵',
        active: true,
        featured: true,
        createdAt: '2026-05-30T10:00:00.000Z',
        image: cover('a11y-lens-devtools'),
        description:
          'افزونه‌ای برای مرورگر که تله‌های صفحه‌کلید، ترتیب فوکوس و آینه‌شدن RTL را در هر صفحه‌ای بررسی می‌کند؛ چون خودم بارها در ریویوهای طراحی شکخوردم.',
        technologies: ['TypeScript', 'React', 'Chrome Extension API', 'axe-core', 'Vite'],
        links: [
          { type: 'سورس', href: 'https://github.com/sara-mirzaei/a11y-lens', icon: 'github' },
          { type: 'مستندات', href: 'https://a11ylens.example.com/docs', icon: 'docs' },
        ],
        details: [
          '## چرا ساخته شد',
          '',
          'در بررسی‌های دسترس‌پذیری نووا همیشه چهار مشکل تکراری پیدا می‌شد: فوکوسی که غیب می‌شود، آیکونی که تنها برچسب یک کنترل است، سطح لمس کوچک‌تر از ۲۴ پیکسل و فلش‌هایی که در RTL برنمی‌گردند. هیچ‌کدام از این‌ها در اسکن خودکار دیده نمی‌شدند.',
          '',
          'A11y Lens به‌جای سورس، صفحه رندرشده را بررسی می‌کند؛ همین است که چیزهایی را می‌بیند که لینترها نمی‌بینند.',
          '',
          '## چه کاری انجام می‌دهد',
          '',
          '- **نقشه فوکوس** ترتیب Tab را با چیپ‌های شماره‌دار روی صفحه نشان می‌دهد و عنصرهای خارج از ویوپورت را علامت می‌زند.',
          '- **تله صفحه‌کلید** ناحیه‌های اسکرول‌شونده و دیالوگ‌هایی که Tab و Escape را می‌بلعند پیدا می‌کند.',
          '- **آینه RTL** بیلد چپ‌به‌راست و راست‌به‌چپ را مقایسه می‌کند و هر آیکون، سایه و transform را که برنگشته لیست می‌کند.',
          '- **بررسی برچسب** کنترل‌هایی را که نام دسترسی‌پذیرشان از placeholder یا هیچ می‌آید افشا می‌کند.',
          '',
          'خروجی به شکل JSON، Markdown یا check run در گیت‌هاب منتشر می‌شود، پس می‌تواند پای یک PR را بگیرد به‌جای اینکه تب دیگری در مرورگر شود.',
          '',
          '## پشت صحنه',
          '',
          'موتور ممیزی یک تابع ناب روی snapshot درخت دسترس‌پذیری است؛ به همین دلیل کل تست‌ها بدون مرورگر اجرا می‌شوند.',
          '',
          '## نتیجه',
          '',
          '| سنجه | مقدار |',
          '| --- | --- |',
          '| نصب | ۴٬۸۰۰ |',
          '| ممیزی فعال هفتگی | ۱٬۱۰۰ |',
          '| میانه یافته‌ها در هر صفحه | ۶ |',
          '| خطاهای RTL گرفته‌شده پیش از QA | ۸۳٪ |',
          '',
          '## پشته فناوری',
          '',
          'TypeScript، React، Manifest V3، axe-core، Vite و Vitest با درخت دسترس‌پذیری jsdom.',
        ].join('\n'),
      },
      {
        title: 'سیستم طراحی نووا',
        slug: 'nova-design-system',
        href: 'https://novads.example.com',
        dates: 'خرداد ۱۴۰۳ - شهریور ۱۴۰۴',
        active: true,
        featured: true,
        createdAt: '2025-09-20T08:00:00.000Z',
        image: cover('nova-design-system'),
        description: 'توکن‌ها، ۱۴۸ کامپوننت و یک مدل مشارکت برای شش تیم محصول؛ یک قطار ارتقا و صفر دکمه سلیقه‌ای.',
        technologies: ['React', 'TypeScript', 'Radix UI', 'Tailwind CSS', 'Style Dictionary', 'Storybook'],
        links: [
          { type: 'وب‌سایت', href: 'https://novads.example.com', icon: 'website' },
          { type: 'مستندات', href: 'https://novads.example.com/docs', icon: 'docs' },
          { type: 'سورس', href: 'https://github.com/sara-mirzaei/nova-ds', icon: 'github' },
        ],
        details: [
          '## مسئله',
          '',
          'شش تیم محصول، سه زبان طراحی و کدبازی که هر دکمه در آن نظری مستقل داشت. ساخت یک فیچر یک هفته طول می‌کرد؛ تصمیم درباره اینکه دکمه کدام تیم استفاده شود، دو روز.',
          '',
          '## چیزی که ساختم',
          '',
          '- **اول توکن.** رنگ، فاصله، تایپ و موشن از یک فایل JSON با Style Dictionary به متغیرهای CSS، preset تیلویند و استایل‌های فیگما کامپایل می‌شوند.',
          '- **۱۴۸ کامپوننت** روی پریمیتیوهای Radix؛ هرکدام با آینه RTL، تم تیره و قرارداد صفحه‌کلید مستندشده در Storybook.',
          '- **قطار ارتقا.** انتشار هفتگی canary، codemod برای تغییرات شکنده و سیاست deprecated شدن که فقط یک ریلیز فرصت واکنش می‌دهد.',
          '- **حاکمیت.** قالب پروپوزال، داشبورد سطح پذیرش و دفتر ساعات هفتگی، بحث «مالک این کامپوننت کیست» را حذف کرد.',
          '',
          '## مهم‌ترین بخش کار',
          '',
          'مشارکت باید کسل‌کننده می‌شد. تیمی که کامپوننت تازه می‌خواهد یک درخواست باز می‌کند، جایگاه در نقشه راه می‌گیرد یا خودش بر پایه API منتشرشده می‌نویسد و ریویو یک چک‌لیست است نه بحث سلیقه. پذیرش در پنج ماه به ۷۱ درصد صفحه‌ها رسید؛ عمدتاً چون «نه» گفتن ارزان بود.',
          '',
          '## نتیجه',
          '',
          '| سنجه | پیش | پس |',
          '| --- | --- | --- |',
          '| میانه زمان ساخت UI | ۶٫۴ روز | ۲٫۱ روز |',
          '| دورهای بازبینی طراحی | ۳٫۱ | ۱٫۲ |',
          '| کامپوننت‌های خارج از الگو | ۲۱۴ | ۲۶ |',
          '| حجم باندل هر صفحه | ۱۸۴ کیلوبایت | ۹۶ کیلوبایت |',
          '',
          '## پشته فناوری',
          '',
          'TypeScript، Radix UI، Tailwind CSS، Style Dictionary، Storybook، رگرسیون بصری Playwright و Changesets.',
        ].join('\n'),
      },
      {
        title: 'بازطراحی ویترین فروشگاه',
        slug: 'vitrin-storefront-redesign',
        href: 'https://vitrin-shop.example.com',
        dates: 'اسفند ۱۴۰۱ - آبان ۱۴۰۲',
        active: true,
        featured: true,
        createdAt: '2023-12-02T09:00:00.000Z',
        image: cover('vitrin-storefront'),
        description:
          'بازسازی فروشگاه با محوریت فارسی: رندر سمت سرور، سبد خرید خوش‌بینانه و فرایند پرداختی که روی اندروید پنج‌ساله با شبکه 3G هم کار می‌کند.',
        technologies: ['Next.js', 'TypeScript', 'React Server Components', 'Tailwind CSS', 'Zustand', 'Playwright'],
        links: [
          { type: 'وب‌سایت', href: 'https://vitrin-shop.example.com', icon: 'website' },
          { type: 'سورس', href: 'https://github.com/sara-mirzaei/vitrin', icon: 'github' },
        ],
        details: [
          '## خواسته',
          '',
          'هفتاد و یک درصد ترافیک موبایل بود، گوشی میانگین چهار سال عمر داشت و شبکه 4G نبود. فروشگاه قدیمی یازده ثانیه طول می‌کشید تا اولین نقاشی معنادار و دو سوم سبدها در گام آدرس رها می‌شدند.',
          '',
          '## تصمیم‌هایی که عدد جابه‌جا کردند',
          '',
          '- **روی سرور رندر کن، هرچیزی را که نمی‌بینی hydrate نکن.** صفحات محصول به React Server Components تبدیل شدند و باندل کلاینت یک صفحه دسته‌بندی از ۴۱۲ به ۹۶ کیلوبایت رسید.',
          '- **وضعیت سبد محلی می‌ماند.** سبد خوش‌بینانه اول در IndexedDB نوشته و بعداً همگام می‌شود، پس افزودن کالا حتی با شبکه کند، آنی پاسخ می‌دهد.',
          '- **فونت به‌جای آیکون.** فونت وب فارسی به ازای هر قالب subset و preload می‌شود و fallback‌هایی که خط‌شکنی می‌کردند حذف شدند.',
          '- **یک کامپوننت ورودی، درست از نظر RTL.** استپر، ماسک و ورودی تلفن یک بار بازسازی شدند و در پرداخت، پشتیبانی و پنل فروشنده مشترک شدند.',
          '',
          '## نتیجه',
          '',
          '| سنجه | پیش | پس |',
          '| --- | --- | --- |',
          '| LCP (p75 موبایل) | ۴٫۱ ثانیه | ۱٫۹ ثانیه |',
          '| CLS | ۰٫۳۱ | ۰٫۰۴ |',
          '| تکمیل خرید | ۶۱٪ | ۷۳٪ |',
          '| پرش در صفحه محصول | ۴۸٪ | ۳۳٪ |',
          '',
          'بودجه عملکرد حالا یک گیت در CI است؛ هر درخواستی که LCP را در پروفایل شبیه‌سازی‌شده از ۲٫۵ ثانیه عبور دهد، رد می‌شود.',
          '',
          '## پشته فناوری',
          '',
          'Next.js App Router، React Server Components، TypeScript، Tailwind CSS، Zustand، Playwright و Web Vitals متصل به Grafana.',
        ].join('\n'),
      },
      {
        title: 'کیت تاریخ جلالی',
        slug: 'persian-date-kit',
        href: 'https://persiandatekit.example.com',
        dates: 'خرداد ۱۴۰۱ - مهر ۱۴۰۱',
        active: true,
        featured: false,
        createdAt: '2022-10-10T07:00:00.000Z',
        image: cover('persian-date-kit'),
        description:
          'کتابخانه ابزار تاریخ جلالی بدون هیچ وابستگی، با قالب‌سازی بر پایه Intl و کامپوننت‌های React سازگار با RTL؛ حدود ۴۰ هزار نصب هفتگی.',
        technologies: ['TypeScript', 'React', 'Intl API', 'Vitest'],
        links: [
          { type: 'سورس', href: 'https://github.com/sara-mirzaei/persian-date-kit', icon: 'github' },
          { type: 'مستندات', href: 'https://persiandatekit.example.com', icon: 'docs' },
          { type: 'npm', href: 'https://www.npmjs.com/package/persian-date-kit', icon: 'download' },
        ],
        details: [
          '## مسئله',
          '',
          'هر پروژه فارسی‌زبانی که به آن پیوستم تاریخ را یکی از روش‌های همیشه‌یکسان حل می‌کرد: جدول تبدیل دست‌نویس کپی‌شده از یک پست سال ۱۳۹۱ که حول نوروز یک روز خطا داشت و برای قالب‌سازی بی‌فایده بود.',
          '',
          '## راهبرد',
          '',
          '- **بدون جدول تبدیل.** تقویم جلالی به `Intl.DateTimeFormat` با پسوند `fa-IR-u-ca-persian` واگذار می‌شود؛ محاسبه با مرورگر، نه با جدول ما.',
          '- **قالب‌سازی از داده locale می‌آید، نه الگوی رشته‌ای.** نام ماه، رقم و جداکننده از Intl می‌آیند، پس ارقام فارسی بعداً باید چسب زده نمی‌شوند.',
          '- **کامپوننت‌ها جهتشان درست است.** `DateField`، `DateRangePicker` و `Calendar` داخل یک گام `dir=\"rtl\"` رندر می‌شوند و فلش‌های خودشان را برمی‌گردانند.',
          '',
          '## آنچه نگه‌داشتنش به من آموخت',
          '',
          'دو سال issue به من یاد داد که یک کتابخانه تاریخ عمدتاً مدیریت خطاست: ورودی نامعتبر، لبه‌های ساعت تابستانی و تقویم‌هایی که درباره سال کبیسه توافق ندارند. API امروز صریح است که کدام تقویم را برمی‌گرداند و هرگز منطقه زمانی را حدس نمی‌زند.',
          '',
          '## پشته فناوری',
          '',
          'TypeScript، Intl، React 19، Vitest با پوشش کامل شاخه‌ها و Size-limit روی ۴٫۲ کیلوبایت gzip.',
        ].join('\n'),
      },
    ],
  },

  posts: {
    en: [
      {
        title: 'Design tokens that survive a rebrand',
        slug: 'design-tokens-that-survive-a-rebrand',
        summary:
          'A rebrand is a rename, not a rewrite. What changed when we moved every colour, space and shadow in Nova behind four layers of tokens.',
        tags: ['design-systems', 'css', 'tokens'],
        published: true,
        createdAt: '2026-06-15T09:00:00.000Z',
        image: cover('design-tokens-rebrand'),
        content: [
          'When Nova announced a rebrand, my first thought was: how many files contain the word `brand-blue`? The honest answer was 612. Eighteen months later, the same rebrand touched three files. The difference was a token structure with four layers and no exceptions.',
          '',
          '## The four layers',
          '',
          '1. **Primitive** — raw values, named by what they are: `blue-500`, `space-4`.',
          '2. **Semantic** — what they mean: `surface-raised`, `text-muted`, `action-primary`.',
          '3. **Component** — what they do locally: `button-bg-hover`, `dialog-shadow`.',
          '4. **Alias** — the escape hatch for a product team that genuinely needs to deviate.',
          '',
          'Nothing in application code reads a primitive. That one rule did most of the work.',
          '',
          '```css',
          '/* Generated: never hand-edited */',
          ':root {',
          '  --color-brand-500: oklch(0.58 0.21 254);',
          '  --surface-raised: var(--color-neutral-0);',
          '  --button-bg-hover: var(--color-brand-600);',
          '}',
          '```',
          '',
          '## Where it paid off',
          '',
          '- Dark mode stopped being a second stylesheet and became a second semantic layer.',
          '- Contrast is checked in CI: every semantic token ships a foreground/background pair, so WCAG 1.4.3 can be verified mechanically.',
          '- The rebrand landed as a PR to one semantic file; component and alias layers did not move.',
          '',
          '## What I would do differently',
          '',
          'I would name the primitives after the palette, not the platform. `blue-500` was fine until the new brand shifted the hue by twelve degrees and every name became a small lie. `brand-500` would have aged better.',
        ].join('\n'),
      },
      {
        title: 'Shipping RTL without forking the codebase',
        slug: 'shipping-rtl-without-forking-the-codebase',
        summary:
          'Logical properties, mirrored icons and one build step: how the Persian version of a product stayed on the same component tree as the English one.',
        tags: ['rtl', 'i18n', 'css'],
        published: true,
        createdAt: '2025-11-08T09:00:00.000Z',
        image: cover('rtl-without-fork'),
        content: [
          'Every RTL project I have joined eventually reaches the same fork: someone copies the stylesheet, flips the `left`s to `right`s, and now there are two codebases that drift apart on the first hotfix.',
          '',
          'The alternative is boring and it works.',
          '',
          '## 1. Never write a physical direction',
          '',
          '```css',
          '/* before */',
          '.card { padding-left: 16px; border-right: 1px solid #000; text-align: left; }',
          '',
          '/* after */',
          '.card { padding-inline-start: 16px; border-inline-end: 1px solid #000; text-align: start; }',
          '```',
          '',
          '`margin-inline`, `inset-inline`, `start-` and `end-` cover almost all of it. A ESLint rule on `left|right` in style files caught the rest.',
          '',
          '## 2. Mirror deliberately, not everywhere',
          '',
          'Chevrons, arrows and progress should flip. Icons that carry a physical metaphor should not: a clock, a save disk, a camera shutter. We keep the flip list in one file and designers review it — that list is the contract.',
          '',
          '## 3. Numbers, dates and the LTR island problem',
          '',
          'A Persian page with an order number, a phone number and an invoice total is three writing directions in one line. Wrap each in a `bdi` with an explicit `dir`, and never rely on the parent direction to guess.',
          '',
          '## 4. Test it like a feature',
          '',
          'Playwright runs the full suite in both directions on every PR. RTL regressions are ordinary test failures rather than a QA discovery two days before release.',
          '',
          'One tree, one stylesheet, one release train. That is the whole trick.',
        ].join('\n'),
      },
      {
        title: 'A performance budget you can actually enforce',
        slug: 'performance-budget-you-can-enforce',
        summary:
          'Lighthouse scores are a screenshot, not a contract. What made our budgets stick: a device profile, a CI gate and a named owner for every regression.',
        tags: ['performance', 'next.js', 'web-vitals'],
        published: true,
        createdAt: '2025-02-19T09:00:00.000Z',
        updatedAt: '2025-06-30T09:00:00.000Z',
        image: cover('performance-budget'),
        content: [
          'We had a performance budget for a year and it changed nothing. It lived in a Notion page, everyone agreed with it, and every page still got slower. Then we made three changes.',
          '',
          '## 1. Write the budget against a device profile',
          '',
          'Not "our homepage" — a device, a network and a percentile:',
          '',
          '```json',
          '{',
          '  "profile": { "cpu": 4, "memory": "2GB", "network": "slow4g", "p": 75 },',
          '  "limits": { "lcp": 2500, "inp": 200, "cls": 0.1, "js": "96KB" }',
          '}',
          '```',
          '',
          'Numbers without a profile are negotiable, and negotiated budgets always lose.',
          '',
          '## 2. Put the gate where the damage happens',
          '',
          'Field data (CrUX, our own RUM) tells you what users experience, but it arrives weeks after the pull request. So CI runs a lab profile per route group and fails the check on the diff, not the absolute value: **+150ms or +8KB to a route = red**.',
          '',
          '## 3. Give every regression an owner and an expiry',
          '',
          'Budget failures can be waived, but a waiver needs a name, a reason and a date. Expired waivers fail the build. That single rule turned performance from a moral argument into a queue with a due date.',
          '',
          '## What the RUM pipeline looks like',
          '',
          '- `web-vitals` on the client, sampled at 10%, batched into a Next.js route handler.',
          '- A nightly aggregation into the dashboards, split by route, device class and locale.',
          '- A weekly digest in the team channel with the three worst routes, not the thirty.',
          '',
          'The result is not that we ship fast. It is that slowing down now costs something visible.',
        ].join('\n'),
      },
      {
        title: 'Notes from running a front-end guild',
        slug: 'notes-from-running-a-front-end-guild',
        summary: 'Six teams, one roadmap and a lot of diplomacy. Working notes on what a guild actually is — and what it is not.',
        tags: ['career', 'design-systems', 'teams'],
        published: false,
        createdAt: '2026-08-20T09:00:00.000Z',
        image: cover('frontend-guild-notes'),
        content: [
          'Draft — collecting notes before the next quarterly review.',
          '',
          '- A guild is not a gate. The moment teams wait for approval, it becomes a bottleneck and they route around it.',
          '- Adoption dashboards beat advocacy. Nobody argues with a chart of who is on which version.',
          '- Office hours are the cheapest interface we have; two hours a week answered more questions than a year of documentation.',
          '- Every breaking change buys itself a codemod, or it does not ship.',
          '',
          'Open questions: how to price internal contribution in performance reviews, and whether one upgrade train per week is still the right cadence at nine teams.',
        ].join('\n'),
      },
    ],
    fa: [
      {
        title: 'توکن‌های طراحی که یک تغییر برند را دوام می‌آورند',
        slug: 'design-tokens-that-survive-a-rebrand',
        summary:
          'تغییر برند یک نام‌گذاری تازه است، نه بازنویسی. چه اتفاقی افتاد وقتی همه رنگ‌ها، فاصله‌ها و سایه‌های نووا را پشت چهار لایه توکن بردیم.',
        tags: ['design-systems', 'css', 'tokens'],
        published: true,
        createdAt: '2026-06-15T09:00:00.000Z',
        image: cover('design-tokens-rebrand'),
        content: [
          'وقتی نووا تغییر برند را اعلام کرد، اولین فکرم این بود: چند فایل کلمه `brand-blue` را دارند؟ پاسخ صادقانه ۶۱۲ بود. هجده ماه بعد، همان تغییر برند سه فایل را لمس کرد. تفاوت، یک ساختار توکنی با چهار لایه و بدون استثنا بود.',
          '',
          '## چهار لایه',
          '',
          '۱. **Primitive** — مقدار خام، با نام آنچه هست: `blue-500`، `space-4`.',
          '۲. **Semantic** — آنچه معنا می‌دهد: `surface-raised`، `text-muted`، `action-primary`.',
          '۳. **Component** — آنچه محلی انجام می‌دهد: `button-bg-hover`، `dialog-shadow`.',
          '۴. **Alias** — راه فرار تیمی که واقعاً باید از الگو خارج شود.',
          '',
          'هیچ‌چیز در کد برنامه نمی‌تواند primitive را بخواند. بیشتر کار همان یک قانون انجام داد.',
          '',
          '## کجا جواب داد',
          '',
          '- تم تیره از یک stylesheet دوم به یک لایه معنایی دوم تبدیل شد.',
          '- کنتراست در CI بررسی می‌شود: هر توکن معنایی یک جفت پیش‌زمینه/پس‌زمینه می‌فرستد، پس WCAG 1.4.3 مکانیکی قابل بررسی است.',
          '- تغییر برند به صورت یک PR به یک فایل معنایی پیاده شد؛ لایه‌های component و alias تکان نخوردند.',
          '',
          '## آنچه را امروز عوض می‌کنم',
          '',
          'primitiveها را به نام پالت می‌نامیدم، نه پلتفرم. `blue-500` تا زمانی خوب بود که برند جدید ته رنگ را دوازده درجه جابه‌جا کرد و هر نام یک دروغ کوچک شد.',
        ].join('\n'),
      },
      {
        title: 'انتشار RTL بدون فورک کردن کدبیس',
        slug: 'shipping-rtl-without-forking-the-codebase',
        summary: 'خاصیت‌های منطقی، آیکون‌های آینه‌شده و یک گام build: چگونه نسخه فارسی یک محصول روی همان درخت کامپوننت نسخه انگلیسی ماند.',
        tags: ['rtl', 'i18n', 'css'],
        published: true,
        createdAt: '2025-11-08T09:00:00.000Z',
        image: cover('rtl-without-fork'),
        content: [
          'هر پروژه RTL که در آن شرکت کرده‌ام بالاخره به همان فورک می‌رسد: یکی stylesheet را کپی می‌کند، همه `left`ها را به `right` تبدیل می‌کند و از آن به بعد دو کدبیس داریم که با اولین hotfix از هم دور می‌شوند.',
          '',
          'راه جایگزین کسل‌کننده است و کار می‌کند.',
          '',
          '## ۱. هرگز جهت فیزیکی ننویسید',
          '',
          'به‌جای `padding-left` از `padding-inline-start`، به‌جای `border-right` از `border-inline-end` و به‌جای `text-align: left` از `text-align: start` استفاده کنید. `margin-inline`، `inset-inline` و پیشوندهای `start-`/`end-` تقریباً همه‌چیز را پوشش می‌دهند؛ یک قانون ESLint روی `left|right` در فایل‌های استایل، باقی را می‌گیرد.',
          '',
          '## ۲. آینه‌کردن را انتخاب کنید، نه همه‌جا',
          '',
          'فلش‌ها، چیولرون‌ها و نوار پیشرفت باید برگردند. آیکون‌هایی که استعاره فیزیکی دارند نباید: ساعت، دیسک ذخیره، شاتر دوربین. فهرست برگرداندن را در یک فایل نگه می‌داریم و طراح آن را ریویو می‌کند؛ همان فهرست، قرارداد است.',
          '',
          '## ۳. عدد، تاریخ و جزیره LTR',
          '',
          'یک صفحه فارسی با شماره سفارش، شماره تلفن و مبلغ فاکتور، سه جهت نوشتاری در یک خط است. هرکدام را در `bdi` با `dir` صریح بپیچید و هرگز به جهت والد اعتماد نکنید.',
          '',
          '## ۴. مثل یک فیچر تستش کنید',
          '',
          'Playwright هر مجموعه را در دو جهت روی هر PR اجرا می‌کند. رگرسیون‌های RTL دیگر کشفِ دو روز قبل از انتشار نیستند؛ یک تست قرمز معمولی‌اند.',
          '',
          'یک درخت، یک stylesheet، یک قطار انتشار. کل ترفند همین است.',
        ].join('\n'),
      },
      {
        title: 'بودجه‌ای که واقعاً قابل اجرا باشد',
        slug: 'performance-budget-you-can-enforce',
        summary: 'نمره Lighthouse یک اسکرین‌شات است، نه قرارداد. سه چیزی که بودجه ما را اجراپذیر کرد: پروفایل دستگاه، گیت CI و یک مالک برای هر افت.',
        tags: ['performance', 'next.js', 'web-vitals'],
        published: true,
        createdAt: '2025-02-19T09:00:00.000Z',
        updatedAt: '2025-06-30T09:00:00.000Z',
        image: cover('performance-budget'),
        content: [
          'یک سال بودجه عملکرد داشتیم و هیچ‌چیز عوض نشد. بودجه در یک صفحه Notion زندگی می‌کرد، همه با آن موافق بودند و صفحه‌ها کندتر می‌شدند. بعد سه تغییر دادیم.',
          '',
          '## ۱. بودجه را با پروفایل دستگاه بنویسید',
          '',
          'نه «صفحه اصلی ما»؛ یک دستگاه، یک شبکه و یک صدک. CPU چهارهسته‌ای، حافظه ۲ گیگابایت، شبکه slow4G و p75. اعداد بدون پروفایل قابل چانه‌زدن‌اند و بودجه چانه‌زده‌شده همیشه می‌بازد.',
          '',
          '## ۲. گیت را همان‌جا بگذارید که آسیب می‌رسد',
          '',
          'داده میدانی (CrUX و RUM خودمان) می‌گوید کاربر چه تجربه می‌کند، اما هفته‌ها بعد از رسیدن PR به مقصد می‌رسد. پس CI یک پروفایل آزمایشگاهی برای هر گروه مسیر اجرا می‌کند و بررسی را بر پایه **diff** قرمز می‌کند، نه مقدار مطلق: ۱۵۰ میلی‌ثانیه یا ۸ کیلوبایت اضافه روی یک مسیر یعنی قرمز.',
          '',
          '## ۳. برای هر افت، مالک و انقضا بگذارید',
          '',
          'قابل بخشودن است، اما بخشش نیاز به نام، دلیل و تاریخ دارد. بخشش‌های منقضی‌شده بیلد را قرمز می‌کنند. همان یک قانون، عملکرد را از بحثی اخلاقی به صفی با سررسید تبدیل کرد.',
          '',
          '## نتیجه',
          '',
          'هدف این نیست که همیشه سریع منتشر کنیم؛ هدف این است که کند شدن، از این پس چیزی قابل‌مشاهده هزینه کند.',
        ].join('\n'),
      },
      {
        title: 'یادداشت‌هایی از اداره گیلد فرانت‌اند',
        slug: 'notes-from-running-a-front-end-guild',
        summary: 'شش تیم، یک نقشه راه و مقدار زیادی دیپلماسی. یادداشت‌های کاری درباره اینکه گیلد واقعاً چیست — و چه چیزی نیست.',
        tags: ['career', 'design-systems', 'teams'],
        published: false,
        createdAt: '2026-08-20T09:00:00.000Z',
        image: cover('frontend-guild-notes'),
        content: [
          'پیش‌نویس — پیش از بازبینی فصلی، یادداشت‌ها را جمع می‌کنم.',
          '',
          '- گیلد، گیت نیست. از لحظه‌ای که تیم‌ها منتظر تأیید بمانند، به گلوگاه تبدیل می‌شود و از آن کنار می‌زنند.',
          '- داشبورد پذیرش، از هر تبلیغی قوی‌تر است. با نموداری که نشان می‌دهد کدام تیم روی کدام نسخه است، کسی بحث نمی‌کند.',
          '- دفتر ساعات هفتگی ارزان‌ترین رابط ماست؛ دو ساعت در هفته بیشتر از یک سال مستند سؤال پاسخ داد.',
          '- هر تغییر شکنده باید برای خودش codemod بخرد، وگرنه منتشر نمی‌شود.',
          '',
          'سؤال‌های باز: سهم مشارکت داخلی در ارزیابی عملکرد چطور قیمت‌گذاری شود، و آیا یک قطار ارتقا در هفته برای نه تیم هنوز ریتم درست است یا نه.',
        ].join('\n'),
      },
    ],
  },
};
