import { bullets, cover, portrait, type Persona } from './types';

/**
 * Alex Carter — full stack developer on small product teams.
 *
 * The original demo identity of the template, written up properly: one person
 * who owns a feature from the database migration to the CSS, plus the project
 * this very site is built from.
 */
export const fullstack: Persona = {
  id: 'fullstack',
  label: 'Full stack developer · product teams',

  profile: {
    en: [
      {
        name: 'Alex',
        fullName: 'Alex Carter',
        jobTitle: 'Full Stack Developer',
        summary:
          'I take products from migration to pixel — TypeScript on both sides, Next.js in the middle, and a strong preference for boring technology.',
        description: [
          'I work the whole seam of a product: the schema, the API, the interface and the pipeline that deploys them. Eight years of that, mostly on small teams where "back end" and "front end" were the same person on different days.',
          '',
          'My bias is toward technology that will still be maintainable in three years: PostgreSQL over whatever is trending, server-rendered pages over a second state store, and features measured in weeks rather than quarters. I have rewritten enough clever systems to prefer dull ones.',
          '',
          '### What I bring to a team',
          '',
          '- End-to-end ownership: migration, API contract, UI, dashboards, alerts',
          '- A feel for the point where a prototype should stop being a prototype',
          "- Writing and reviews that make the next person's week easier",
          '- An unreasonable fondness for keyboard shortcuts and keyboard-only flows',
          '',
          'I build this portfolio, maintain a self-hosted invoicing app, and write about the boring parts of shipping software.',
        ].join('\n'),
        avatarUrl: portrait('alex-carter'),
        tel: '+49 30 5555 0182',
        email: 'hello@alexcarter.dev',
      },
    ],
    fa: [
      {
        name: 'الکس',
        fullName: 'الکس کارتر',
        jobTitle: 'توسعه‌دهنده فول استک',
        summary: 'محصول را از مهاجرت دیتابیس تا پیکسل جلو می‌برم؛ TypeScript در دو طرف، Next.js وسط و ترجیحی جدی برای فناوری کسل‌کننده.',
        description: [
          'کل درز یک محصول را کار می‌کنم: schema، API، رابط کاربری و پایپ‌لینی که این‌ها را دیپلوی می‌کند. هشت سال از این کار، بیشتر در تیم‌های کوچک که «بک‌اند» و «فرانت‌اند» در روزهای مختلف همان یک نفر بودند.',
          '',
          'سوالم به سمت فناوری‌ای است که سه سال دیگر هم قابل نگه‌داشتن باشد: PostgreSQL به‌جای هر چیزی که ترند است، صفحه رندرشده سمت سرور به‌جای یک استور state دوم، و فیچری که بر حسب هفته تعریف می‌شود نه فصل. آن‌قدر سیستم‌های باهوش را بازنویسی کرده‌ام که سیستم‌های معمولی را ترجیح می‌دهم.',
          '',
          '### چه چیزی به تیم می‌آورم',
          '',
          '- مالکیت سرتاسری: مهاجرت، قرارداد API، UI، داشبورد و alert',
          '- حس لحظه‌ای که یک prototype باید دیگر prototype نباشد',
          '- نوشتن و ریویویی که هفته نفر بعدی را آسان‌تر کند',
          '- علاقه‌ای بی‌دلیل به میان‌برهای صفحه‌کلید و جریان‌های فقط-با-صفحه‌کلید',
          '',
          'این نمونه‌کار را خودم ساخته‌ام، یک اپ فاکتور خودمیزبان را نگه می‌دارم و درباره بخش‌های کسل‌کننده نرم‌افزار نوشتن می‌نویسم.',
        ].join('\n'),
        avatarUrl: portrait('alex-carter'),
        tel: '۰۳۰ ۵۵۵۵ ۰۱۸۲',
        email: 'hello@alexcarter.dev',
      },
    ],
  },

  socials: {
    en: [
      { name: 'Website', url: 'https://alexcarter.dev', icon: 'website' },
      { name: 'GitHub', url: 'https://github.com/alexcarter', icon: 'github' },
      { name: 'LinkedIn', url: 'https://www.linkedin.com/in/alexcarter', icon: 'linkedin' },
      { name: 'X', url: 'https://x.com/alexcarterdev', icon: 'x' },
    ],
    fa: [
      { name: 'وب‌سایت', url: 'https://alexcarter.dev', icon: 'website' },
      { name: 'گیت‌هاب', url: 'https://github.com/alexcarter', icon: 'github' },
      { name: 'لینکدین', url: 'https://www.linkedin.com/in/alexcarter', icon: 'linkedin' },
      { name: 'ایکس', url: 'https://x.com/alexcarterdev', icon: 'x' },
    ],
  },

  skills: {
    en: [
      { name: 'TypeScript' },
      { name: 'JavaScript' },
      { name: 'React' },
      { name: 'Next.js' },
      { name: 'Node.js' },
      { name: 'Express' },
      { name: 'MongoDB' },
      { name: 'PostgreSQL' },
      { name: 'Prisma' },
      { name: 'Redis' },
      { name: 'GraphQL' },
      { name: 'Tailwind CSS' },
      { name: 'Docker' },
      { name: 'AWS' },
      { name: 'Vitest & Playwright' },
      { name: 'CI/CD' },
    ],
    fa: [
      { name: 'TypeScript' },
      { name: 'JavaScript' },
      { name: 'React' },
      { name: 'Next.js' },
      { name: 'Node.js' },
      { name: 'Express' },
      { name: 'MongoDB' },
      { name: 'PostgreSQL' },
      { name: 'Prisma' },
      { name: 'Redis' },
      { name: 'GraphQL' },
      { name: 'Tailwind CSS' },
      { name: 'Docker' },
      { name: 'AWS' },
      { name: 'تست با Vitest و Playwright' },
      { name: 'CI/CD' },
    ],
  },

  educations: {
    en: [
      {
        school: 'Delft University of Technology',
        degree: 'M.Sc. Computer Science',
        href: 'https://tudelft.nl',
        logoUrl: '',
        start: '2015/09',
        end: '2017/07',
      },
      {
        school: 'University of Nottingham',
        degree: 'B.Sc. Computer Science with Industrial Experience',
        href: 'https://nottingham.ac.uk',
        logoUrl: '',
        start: '2012/09',
        end: '2015/07',
      },
    ],
    fa: [
      {
        school: 'دانشگاه صنعتی دلفت',
        degree: 'کارشناسی ارشد علوم کامپیوتر',
        href: 'https://tudelft.nl',
        logoUrl: '',
        start: '1394/06',
        end: '1396/04',
      },
      {
        school: 'دانشگاه ناتینگهام',
        degree: 'کارشناسی علوم کامپیوتر با دوره صنعتی',
        href: 'https://nottingham.ac.uk',
        logoUrl: '',
        start: '1391/06',
        end: '1394/04',
      },
    ],
  },

  works: {
    en: [
      {
        company: 'Loop Analytics',
        title: 'Senior Full Stack Engineer',
        location: 'Berlin, Germany',
        href: 'https://loopanalytics.example.com',
        logoUrl: '',
        start: '2024/02',
        end: '',
        description: bullets(
          'Own the reporting surface end to end: Postgres rollups, a tRPC API and the Next.js dashboard that reads them.',
          'Rebuilt CSV/Excel exports as streaming responses; a 90-second job now finishes in under four.',
          'Cut cloud spend 22% by replacing two managed services with one Postgres and a cron.',
          'Pair with the two other engineers on review etiquette and incident review.'
        ),
      },
      {
        company: 'Nimbus Labs',
        title: 'Full Stack Developer',
        location: 'Remote',
        href: 'https://nimbuslabs.example.com',
        logoUrl: '',
        start: '2021/06',
        end: '2024/01',
        description: bullets(
          'Shipped customer-facing features with React, Node.js and MongoDB; migrated 40 legacy pages to the Next.js App Router.',
          'Built the webhook delivery service: retries, dead-letter queue and a delivery dashboard support still uses.',
          'Introduced typed API contracts, which removed the class of bugs that filled our issue tracker.'
        ),
      },
      {
        company: 'Studio Nor',
        title: 'Frontend Developer',
        location: 'Lisbon, Portugal',
        href: 'https://studionor.example.com',
        logoUrl: '',
        start: '2019/03',
        end: '2021/05',
        description: bullets(
          'Eleven client sites and two web apps, usually with one designer and a three-week budget.',
          "Built the studio's component starter, halving project setup time."
        ),
      },
      {
        company: 'Freelance',
        title: 'Web Developer',
        location: 'Remote',
        href: '',
        logoUrl: '',
        start: '2017/09',
        end: '2019/02',
        description: bullets(
          'WordPress to React rescues, API integrations and a lot of explaining why the estimate doubled.',
          'Learned to write software that someone has to maintain after I leave.'
        ),
      },
    ],
    fa: [
      {
        company: 'لوپ آنالیتیکس',
        title: 'مهندس ارشد فول استک',
        location: 'برلین، آلمان',
        href: 'https://loopanalytics.example.com',
        logoUrl: '',
        start: '1402/11',
        end: '',
        description: bullets(
          'مالکیت سرتاسری صفحه گزارش‌ها: rollup در Postgres، API روی tRPC و داشبورد Next.js که از آن‌ها می‌خواند.',
          'بازسازی خروجی CSV/Excel به شکل استریم؛ کاری که نود ثانیه طول می‌کشید به زیر چهار ثانیه رسید.',
          'کاهش ۲۲ درصد هزینه کلاود با حذف دو سرویس managed و جایگزینی آن‌ها با یک Postgres و یک cron.',
          'همکاری با دو مهندس دیگر در آداب ریویو و بازبینی رخدادها.'
        ),
      },
      {
        company: 'نیمبس لبز',
        title: 'توسعه‌دهنده فول استک',
        location: 'دورکاری',
        href: 'https://nimbuslabs.example.com',
        logoUrl: '',
        start: '1400/04',
        end: '1402/10',
        description: bullets(
          'انتشار قابلیت‌های سمت کاربر با React، Node.js و MongoDB؛ مهاجرت ۴۰ صفحه قدیمی به Next.js App Router.',
          'ساخت سرویس تحویل webhook با retry، صف مرده و داشبوردی که تیم پشتیبانی هنوز استفاده می‌کند.',
          'معرفی قرارداد تایپ‌شده API؛ همان کاری که دسته باگ‌های پرکننده issue tracker را حذف کرد.'
        ),
      },
      {
        company: 'استودیو نور',
        title: 'توسعه‌دهنده فرانت‌اند',
        location: 'لیسبون، پرتغال',
        href: 'https://studionor.example.com',
        logoUrl: '',
        start: '1397/12',
        end: '1400/02',
        description: bullets(
          'یازده سایت مشتری و دو وب‌اپ؛ معمولاً با یک طراح و بودجه سه‌هفته‌ای.',
          'ساخت starter کامپوننت استودیو که زمان راه‌اندازی پروژه را نصف کرد.'
        ),
      },
      {
        company: 'فریلنس',
        title: 'توسعه‌دهنده وب',
        location: 'دورکاری',
        href: '',
        logoUrl: '',
        start: '1396/06',
        end: '1397/11',
        description: bullets(
          'نجات پروژه‌های WordPress به React، اتصال API و توضیح اینکه چرا برآورد دو برابر شد.',
          'یاد گرفتم نرم‌افزاری بنویسم که بعد از رفتن من هم باید نگه داشته شود.'
        ),
      },
    ],
  },

  projects: {
    en: [
      {
        title: 'Ledgerly',
        slug: 'ledgerly',
        href: 'https://ledgerly.example.com',
        dates: 'March 2025 - February 2026',
        active: true,
        featured: true,
        createdAt: '2026-03-01T08:00:00.000Z',
        image: cover('ledgerly-invoicing'),
        description:
          'Self-hosted invoicing for freelancers: one Docker container, one Postgres, no subscription. 3,100 installs and a paid hosted tier that funds the rest.',
        technologies: ['Next.js', 'TypeScript', 'PostgreSQL', 'Prisma', 'Docker', 'Stripe'],
        links: [
          { type: 'Website', href: 'https://ledgerly.example.com', icon: 'website' },
          { type: 'Source', href: 'https://github.com/alexcarter/ledgerly', icon: 'github' },
          { type: 'Docs', href: 'https://ledgerly.example.com/docs', icon: 'docs' },
        ],
        details: [
          '## Why self-hosted',
          '',
          'Invoicing is the most boring software in the world, and every vendor charges monthly for it while holding the data I need most. Ledgerly is one container and one database: your numbers stay yours, and the PDFs are generated on your machine.',
          '',
          '## Architecture',
          '',
          '- **One binary, two modes.** The same Next.js app runs as the hosted product and as the self-hosted container; the difference is a single capability flag, so the two never drift.',
          '- **Money is integers.** Every amount is stored in the smallest unit as an integer; formatting happens at the edge. No float rounding, ever.',
          '- **Documents are HTML first.** Invoice PDFs render from the same React tree as the preview, through a headless Chromium pool — what you see is literally what ships.',
          '- **Payments are optional.** Stripe connect for the hosted tier; a self-hosted install can just mark an invoice paid.',
          '',
          '```ts',
          '// money never touches a float',
          'type MinorUnits = number & { readonly brand: "minor" };',
          '',
          'export function totalOf(lines: Line[]): MinorUnits {',
          '  return lines.reduce((sum, l) => sum + l.unitPrice * l.quantity, 0) as MinorUnits;',
          '}',
          '```',
          '',
          '## The business part',
          '',
          "The hosted tier is what pays for the project: 190 subscribers, roughly 61% of costs, and a pricing page that says plainly why the self-hosted version will stay free. The two hardest features were not features — password reset email deliverability and an import that survives other tools' exports.",
          '',
          '## Numbers',
          '',
          '| Measure | Result |',
          '| --- | --- |',
          '| Installs (GitHub releases) | 3,100 |',
          '| Hosted subscribers | 190 |',
          '| Invoices generated per month | 24,000 |',
          '| Support tickets per 100 users | 1.4 |',
          '',
          '## Stack',
          '',
          'Next.js, TypeScript, PostgreSQL, Prisma, Auth.js, Stripe, Tailwind CSS, headless Chromium, Docker, Fly.io.',
        ].join('\n'),
      },
      {
        title: 'Monochrome Portfolio',
        slug: 'monochrome-portfolio',
        href: 'https://github.com/alexcarter/monochrome-portfolio',
        dates: 'June 2025 - Present',
        active: true,
        featured: true,
        createdAt: '2025-07-15T08:00:00.000Z',
        image: cover('monochrome-portfolio'),
        description:
          'The engine behind this site: a bilingual, RTL-capable portfolio with a dashboard, blog and one-command deploy. Open source, and the reason the Persian version exists.',
        technologies: ['Next.js', 'MongoDB', 'Tailwind CSS', 'shadcn/ui', 'next-intl', 'NextAuth'],
        links: [
          { type: 'Source', href: 'https://github.com/alexcarter/monochrome-portfolio', icon: 'github' },
          { type: 'Docs', href: 'https://alexcarter.dev/monochrome', icon: 'docs' },
        ],
        details: [
          '## The point',
          '',
          'A portfolio should sell the work, not the decoration. This site is a strict black-and-white palette, one typeface per language, a handful of quiet animations, and content that is entirely editable from `/dashboard` without a redeploy.',
          '',
          '## Rules it keeps',
          '',
          '- **Two locales, one tree.** English and Persian share every component. RTL comes from logical properties and a `dir` on the document, never from a forked stylesheet.',
          '- **Content is data.** Profile, projects, roles, education, skills, socials and posts all live in MongoDB and are edited in the dashboard; the public pages read through one data layer that degrades to empty states when the database is unreachable.',
          '- **No client-side data fetching for public pages.** Server components own the read path; the dashboard owns the write path.',
          '- **The quality gate is one command.** Lint, typecheck and build run together, locally and in CI.',
          '',
          '```ts',
          '// one read path, locale-scoped, safe when the DB is down',
          'export async function getPortfolioData(locale: AppLocale): Promise<PortfolioData> {',
          '  if (!(await tryConnectDB())) return EMPTY_PORTFOLIO;',
          '  // ... profile, projects, works, education, skills, socials',
          '}',
          '```',
          '',
          '## What I would change',
          '',
          'Media storage depends on Vercel Blob, which is a fair default for the template and an unreasonable lock-in for a self-hosted install. A pluggable uploader is next on the list.',
          '',
          '## Stack',
          '',
          'Next.js App Router, React Server Components, MongoDB with Mongoose, Tailwind CSS, shadcn/ui, next-intl, NextAuth, TanStack Query on the dashboard.',
        ].join('\n'),
      },
      {
        title: 'DevBoard',
        slug: 'devboard',
        href: 'https://devboard.example.com',
        dates: 'January 2024 - May 2024',
        active: true,
        featured: true,
        createdAt: '2024-06-10T08:00:00.000Z',
        image: cover('devboard-kanban'),
        description:
          'A self-hosted kanban board for engineering teams: realtime collaboration, keyboard-first navigation and no feature you cannot turn off.',
        technologies: ['Next.js', 'TypeScript', 'MongoDB', 'WebSockets', 'Docker'],
        links: [
          { type: 'Website', href: 'https://devboard.example.com', icon: 'website' },
          { type: 'Source', href: 'https://github.com/alexcarter/devboard', icon: 'github' },
        ],
        details: [
          '## The problem',
          '',
          'My team wanted a board, not a project-management product. Every tool we tried had a sprint, a roadmap, an AI summary and a pricing page with our headcount on it. So I built the twelve percent we actually used.',
          '',
          '## Design decisions',
          '',
          '- **Everything is a card, cards are ordered by a float** with a fractional-index rebalance pass, so two users dragging at once converge instead of fighting.',
          '- **Optimistic by default.** The UI writes first and reconciles over a WebSocket; a merge conflict falls back to the server value with a toast, which turned out to be acceptable about ninety percent of the time.',
          '- **Keyboard-first.** `c` to create, `m` to move, `a` to assign, `?` for the cheat sheet. Every action has a binding or does not exist.',
          '- **Features are flags.** Labels, filters, swimlanes and templates can each be switched off for an instance. A board with the features you do not use is a board you will open tomorrow.',
          '',
          '## Hard lesson',
          '',
          'Realtime is a product decision, not a library. Presence, offline queues and reconnect behaviour needed more code than the board itself, and each of them was invisible until it broke.',
          '',
          '## Results',
          '',
          '| Measure | Result |',
          '| --- | --- |',
          '| Instances running | 640 |',
          '| Median interaction latency | 40 ms |',
          '| Weekly active seats (our own team) | 14 |',
          '',
          '## Stack',
          '',
          'Next.js, TypeScript, MongoDB, ws, Docker, Playwright for the multiplayer tests that spin up two browsers and argue.',
        ].join('\n'),
      },
      {
        title: 'Nimbus Sync',
        slug: 'nimbus-sync',
        href: 'https://nimbuslabs.example.com/sync',
        dates: 'February 2023 - October 2023',
        active: true,
        featured: false,
        createdAt: '2023-11-02T08:00:00.000Z',
        image: cover('nimbus-sync-webhooks'),
        description:
          'The webhook delivery service behind Nimbus Labs: retries with jittered backoff, a dead-letter queue, signed payloads and a delivery log support can read.',
        technologies: ['Node.js', 'TypeScript', 'MongoDB', 'Redis', 'BullMQ', 'OpenTelemetry'],
        links: [
          { type: 'Docs', href: 'https://nimbuslabs.example.com/sync/docs', icon: 'docs' },
          { type: 'Source', href: 'https://github.com/alexcarter/nimbus-sync', icon: 'github' },
        ],
        details: [
          '## Before this service',
          '',
          'Webhooks were fired inline from the API. A slow customer endpoint meant a slow request, and a failing one meant a silently lost event. Nobody could answer "did we tell them?"',
          '',
          '## How it works',
          '',
          '1. The API writes an event and a delivery intent in one MongoDB transaction.',
          '2. A worker fleet drains per-endpoint queues, so one dead customer endpoint cannot starve the others.',
          '3. Failures retry with jittered exponential backoff across six hours, then park in a dead-letter queue.',
          '4. Every attempt is a row: request, response, latency, signature, and a replay button.',
          '',
          '```ts',
          '// one queue per endpoint — noisy neighbours stay noisy alone',
          'const queue = new Queue(`deliver:${subscription.id}`, {',
          '  defaultJobOptions: {',
          '    attempts: 8,',
          "    backoff: { type: 'exponential', delay: 5_000 },",
          '    removeOnComplete: 1_000,',
          '  },',
          '});',
          '```',
          '',
          '## Results',
          '',
          '| Measure | Before | After |',
          '| --- | --- | --- |',
          '| Delivered within 1 minute | 91.4% | 99.6% |',
          '| Events lost silently | ~30/month | 0 |',
          '| P95 API latency on publish | 620 ms | 85 ms |',
          '| "Did we deliver?" tickets | 26/week | 4/week |',
          '',
          'The replay button deleted an entire category of support escalation, which is the most underrated feature I have ever shipped.',
          '',
          '## Stack',
          '',
          'Node.js, TypeScript, MongoDB change streams, Redis with BullMQ, OpenTelemetry, Grafana.',
        ].join('\n'),
      },
    ],
    fa: [
      {
        title: 'لجرلی',
        slug: 'ledgerly',
        href: 'https://ledgerly.example.com',
        dates: 'اسفند ۱۴۰۳ - بهمن ۱۴۰۴',
        active: true,
        featured: true,
        createdAt: '2026-03-01T08:00:00.000Z',
        image: cover('ledgerly-invoicing'),
        description:
          'فاکتور خودمیزبان برای فریلنسرها: یک کانتینر Docker، یک Postgres و بدون اشتراک. ۳٬۱۰۰ نصب و یک پلن میزبانی‌شده پولی که بقیه را تأمین می‌کند.',
        technologies: ['Next.js', 'TypeScript', 'PostgreSQL', 'Prisma', 'Docker', 'Stripe'],
        links: [
          { type: 'وب‌سایت', href: 'https://ledgerly.example.com', icon: 'website' },
          { type: 'سورس', href: 'https://github.com/alexcarter/ledgerly', icon: 'github' },
          { type: 'مستندات', href: 'https://ledgerly.example.com/docs', icon: 'docs' },
        ],
        details: [
          '## چرا خودمیزبان',
          '',
          'فاکتور کسل‌کننده‌ترین نرم‌افزار دنیاست و هر فروشنده‌ای ماهانه بابتش پول می‌گیرد، در حالی داده‌ای را نگه داشته که بیشتر از همه به آن نیاز دارم. لجرلی یک کانتینر و یک دیتابیس است: عددت مال خودت می‌ماند و PDF روی دستگاه تو تولید می‌شود.',
          '',
          '## معماری',
          '',
          '- **یک باینری، دو حالت.** همان اپ Next.js هم به شکل محصول میزبانی‌شده و هم کانتینر خودمیزبان اجرا می‌شود؛ تفاوت در یک فلگ توانمندی است، پس این دو هرگز از هم دور نمی‌افتند.',
          '- **پول عدد صحیح است.** هر مبلغ در کوچک‌ترین واحد به شکل integer ذخیره و فقط در لبه قالب‌گیری می‌شود؛ گرد کردن اعشاری هرگز.',
          '- **سند اول HTML است.** PDF فاکتور از همان درخت React که پیش‌نمایش رندر می‌شود، با یک استخر Chromium بدون رابط؛ چیزی که می‌بینید عیناً چیزی است که ارسال می‌شود.',
          '- **پرداخت اختیاری است.** برای پلن میزبانی Stripe Connect؛ در نصب خودمیزبان می‌شود فاکتور را دستی پرداخت‌شده علامت زد.',
          '',
          '## بخش کسب‌وکاری',
          '',
          'پلن میزبانی‌شده پول این پروژه را می‌دهد: ۱۹۰ مشترک، حدود ۶۱ درصد هزینه‌ها و یک صفحه قیمت که صریح می‌گوید نسخه خودمیزبان رایگان می‌ماند. دو سخت‌ترین فیچر فیچر نبودند؛ تحویل ایمیل بازیابی رمز و یک import که از خروجی ابزارهای دیگر زنده بیرون بیاید.',
          '',
          '## اعداد',
          '',
          '| سنجه | مقدار |',
          '| --- | --- |',
          '| نصب (ریلیز گیت‌هاب) | ۳٬۱۰۰ |',
          '| مشترک پلن میزبانی | ۱۹۰ |',
          '| فاکتور تولیدشده در ماه | ۲۴٬۰۰۰ |',
          '| تیکت پشتیبانی به ازای هر ۱۰۰ کاربر | ۱٫۴ |',
          '',
          '## پشته فناوری',
          '',
          'Next.js، TypeScript، PostgreSQL، Prisma، Auth.js، Stripe، Tailwind CSS، Chromium بدون رابط، Docker و Fly.io.',
        ].join('\n'),
      },
      {
        title: 'نمونه‌کار مونوکروم',
        slug: 'monochrome-portfolio',
        href: 'https://github.com/alexcarter/monochrome-portfolio',
        dates: 'تیر ۱۴۰۴ - اکنون',
        active: true,
        featured: true,
        createdAt: '2025-07-15T08:00:00.000Z',
        image: cover('monochrome-portfolio'),
        description:
          'موتور همین سایتی که می‌بینید: نمونه‌کاری دوزبانه با پشتیبانی RTL، داشبورد، وبلاگ و دیپلوی با یک دستور. اوپن‌سورس، و دلیل اینکه نسخه فارسی وجود دارد.',
        technologies: ['Next.js', 'MongoDB', 'Tailwind CSS', 'shadcn/ui', 'next-intl', 'NextAuth'],
        links: [
          { type: 'سورس', href: 'https://github.com/alexcarter/monochrome-portfolio', icon: 'github' },
          { type: 'مستندات', href: 'https://alexcarter.dev/monochrome', icon: 'docs' },
        ],
        details: [
          '## هدف',
          '',
          'نمونه‌کار باید کار را بفروشد، نه تزئینات خودش را. این سایت یک پالت کاملاً سیاه‌وسفید است، یک فونت برای هر زبان، چند انیمیشن بی‌صدا و محتوایی که بی‌نیاز از دیپلوی دوباره، کامل از `/dashboard` ویرایش می‌شود.',
          '',
          '## قوانینی که نگه داشته می‌شود',
          '',
          '- **دو زبان، یک درخت.** انگلیسی و فارسی همه کامپوننت‌ها را مشترک دارند. RTL از خاصیت‌های منطقی و یک `dir` روی سند می‌آید، نه از یک stylesheet دوشاخه.',
          '- **محتوا داده است.** پروفایل، پروژه‌ها، سوابق شغلی، تحصیلات، مهارت‌ها، شبکه‌های اجتماعی و نوشته‌ها همه در MongoDB هستند؛ صفحه‌های عمومی از یک لایه داده می‌خوانند که وقتی دیتابیس در دسترس نیست به حالت خالی تنزل می‌کند.',
          '- **بدون fetch سمت کاربر برای صفحات عمومی.** مسیر خواندن دست Server Components است و مسیر نوشتن دست داشبورد.',
          '- **گیت کیفیت یک دستور است.** لینت، تایپ‌چک و بیلد با هم اجرا می‌شوند، محلی و در CI.',
          '',
          '## آنچه عوض می‌کنم',
          '',
          'ذخیره رسانه به Vercel Blob وابسته است؛ برای این تمپلیت پیش‌فرض منصفانه‌ای است و برای یک نصب خودمیزبان قفل‌کردن بی‌دلیل. یک uploader قابل‌تعویض، اولویت بعدی است.',
          '',
          '## پشته فناوری',
          '',
          'Next.js App Router، React Server Components، MongoDB با Mongoose، Tailwind CSS، shadcn/ui، next-intl، NextAuth و در داشبورد TanStack Query.',
        ].join('\n'),
      },
      {
        title: 'دِو‌بورد',
        slug: 'devboard',
        href: 'https://devboard.example.com',
        dates: 'دی ۱۴۰۲ - اردیبهشت ۱۴۰۳',
        active: true,
        featured: true,
        createdAt: '2024-06-10T08:00:00.000Z',
        image: cover('devboard-kanban'),
        description: 'بورد کانبان خودمیزبان برای تیم‌های مهندسی: همکاری بلادرنگ، پیمایش با صفحه‌کلید و هیچ قابلیت‌ای که خاموش‌کردنی نباشد.',
        technologies: ['Next.js', 'TypeScript', 'MongoDB', 'WebSockets', 'Docker'],
        links: [
          { type: 'وب‌سایت', href: 'https://devboard.example.com', icon: 'website' },
          { type: 'سورس', href: 'https://github.com/alexcarter/devboard', icon: 'github' },
        ],
        details: [
          '## مسئله',
          '',
          'تیم ما یک بورد می‌خواست، نه یک محصول مدیریت پروژه. هر ابزاری که امتحان کردیم اسپرینت داشت، نقشه راه داشت، خلاصه AI داشت و صفحه قیمتی که تعداد نفرات ما در آن نوشته شده بود. پس دوازده درصدی را ساختم که واقعاً استفاده‌اش می‌کردیم.',
          '',
          '## تصمیم‌های طراحی',
          '',
          '- **همه‌چیز کارت است و کارت‌ها با یک عدد اعشاری ترتیب می‌گیرند**، با یک پاس rebalance کسری؛ دو کاربر که هم‌زمان کارت می‌کشند به هم می‌رسند، نمی‌جنگند.',
          '- **پیش‌فرض خوش‌بینانه.** رابط اول می‌نویسد و روی WebSocket همگام می‌شود؛ در تعارض merge، مقدار سرور با یک toast برگردانده می‌شود و تقریباً نود درصد وقت‌ها این قابل قبول بود.',
          '- **اول صفحه‌کلید.** `c` برای ساخت، `m` برای جابه‌جایی، `a` برای انتصاب و `?` برای برگه میان‌برها. هر عملیاتی بایندینگ دارد یا وجود ندارد.',
          '- **قابلیت‌ها فلگ‌اند.** برچسب، فیلتر، lane و قالب برای هر instance جدا خاموش می‌شوند. بوردی که قابلیت‌های به‌دردنخور ندارد، بوردی است که فردا هم بازش می‌کنی.',
          '',
          '## درس سخت',
          '',
          'بلادرنگ بودن تصمیم محصولی است نه انتخاب یک کتابخانه. presence، صف آفلاین و رفتار reconnect از خودِ بورد کد بیشتری خواست و هرکدام تا لحظه شکستن، نامرئی بودند.',
          '',
          '## نتیجه',
          '',
          '| سنجه | مقدار |',
          '| --- | --- |',
          '| instance در حال اجرا | ۶۴۰ |',
          '| میانه تأخیر تعامل | ۴۰ میلی‌ثانیه |',
          '| صندلی فعال هفتگی در تیم خودمان | ۱۴ |',
          '',
          '## پشته فناوری',
          '',
          'Next.js، TypeScript، MongoDB، ws، Docker و Playwright برای تست‌های چندنفره‌ای که دو مرورگر را بالا می‌آورند و بحث می‌کنند.',
        ].join('\n'),
      },
      {
        title: 'نیمبس سینک',
        slug: 'nimbus-sync',
        href: 'https://nimbuslabs.example.com/sync',
        dates: 'بهمن ۱۴۰۱ - مهر ۱۴۰۲',
        active: true,
        featured: false,
        createdAt: '2023-11-02T08:00:00.000Z',
        image: cover('nimbus-sync-webhooks'),
        description:
          'سرویس تحویل webhook پشت نیمبس لبز: retry با backoff پل‌کانی، صف مرده، payload امضاشده و لاگ تحویلی که پشتیبانی می‌تواند بخواند.',
        technologies: ['Node.js', 'TypeScript', 'MongoDB', 'Redis', 'BullMQ', 'OpenTelemetry'],
        links: [
          { type: 'مستندات', href: 'https://nimbuslabs.example.com/sync/docs', icon: 'docs' },
          { type: 'سورس', href: 'https://github.com/alexcarter/nimbus-sync', icon: 'github' },
        ],
        details: [
          '## پیش از این سرویس',
          '',
          'webhookها درون خود API شلیک می‌شدند. یک endpoint کند یعنی یک درخواست کند، و یک endpoint خراب یعنی رویدادی که بی‌صدا گم می‌شود. هیچ‌کس نمی‌توانست به این سؤال جواب دهد «بهشان گفتیم یا نه؟»',
          '',
          '## چطور کار می‌کند',
          '',
          '۱. API در همان یک تراکنش MongoDB، رویداد و قصد تحویل را می‌نویسد.',
          '۲. ناوگان worker صف‌های مجزا به ازای هر endpoint را تخلیه می‌کند، پس یک endpoint مرده نمی‌تواند بقیه را گرسنه نگه دارد.',
          '۳. خطاها با backoff نمایی و jitter تا شش ساعت retry می‌شوند و بعد در صف مرده پارک می‌کنند.',
          '۴. هر تلاش یک ردیف است: درخواست، پاسخ، تأخیر، امضا و یک دکمه replay.',
          '',
          '## نتیجه',
          '',
          '| سنجه | پیش | پس |',
          '| --- | --- | --- |',
          '| تحویل زیر یک دقیقه | ۹۱٫۴٪ | ۹۹٫۶٪ |',
          '| رویداد گم‌شده بی‌صدا | حدود ۳۰ در ماه | ۰ |',
          '| تأخیر p95 API در انتشار | ۶۲۰ میلی‌ثانیه | ۸۵ میلی‌ثانیه |',
          '| تیکت «تحویل دادیم؟» | ۲۶ در هفته | ۴ در هفته |',
          '',
          'همان دکمه replay یک دسته کامل از escalation پشتیبانی را حذف کرد؛ این کم‌قدرت‌نمایی‌شده‌ترین فیچری است که تا حالا منتشر کرده‌ام.',
          '',
          '## پشته فناوری',
          '',
          'Node.js، TypeScript، change stream در MongoDB، Redis با BullMQ، OpenTelemetry و Grafana.',
        ].join('\n'),
      },
    ],
  },

  posts: {
    en: [
      {
        title: 'Prisma migrations in production: the rules we broke once',
        slug: 'prisma-migrations-in-production',
        summary:
          'A schema change took the invoicing app down for eleven minutes. Here is the runbook we wrote afterwards, and the four rules it reduced to.',
        tags: ['postgresql', 'prisma', 'devops'],
        published: true,
        createdAt: '2026-02-11T09:00:00.000Z',
        image: cover('prisma-migrations'),
        content: [
          'Eleven minutes of downtime for a change that added a column. The migration was correct; the order of operations was not. This is the write-up I wished I had before that afternoon.',
          '',
          '## What actually happened',
          '',
          '`prisma migrate deploy` wrapped three statements in one transaction: add a column, backfill it with a default, then add a unique index. The backfill locked a table that was busy, the index build waited on it, and every write behind it queued up like traffic behind an accident.',
          '',
          '## The rules that came out of it',
          '',
          '1. **Split additive from destructive.** A migration either adds or removes, never both. Removing gets its own release, after nothing writes to the old shape.',
          '2. **Never backfill inside the migration.** A batched job you can pause beats a lock you cannot interrupt.',
          '3. **Build indexes outside the transaction.** `CREATE INDEX CONCURRENTLY` in a raw migration step — Prisma supports it, and it will not hold a write lock.',
          '4. **Read from the new shape, write to both, then read from the new one.** Three deploys per breaking change. It feels slow until the second one.',
          '',
          '```prisma',
          '// additive only: safe to deploy alongside the old code',
          'model Invoice {',
          '  id          String  @id @default(uuid())',
          '  totalMinor  Int',
          '  currency    String? // nullable, backfilled by a job',
          '}',
          '```',
          '',
          '## The part nobody warns you about',
          '',
          'Migration history is a shared file with a merge strategy nobody owns. Two branches, two `migration.sql`, one conflict resolved by whoever rebased last. We now run `prisma migrate diff` against the shadow database in CI, so a drift between schema and history fails the pull request before it can fail production.',
        ].join('\n'),
      },
      {
        title: 'Server components, two years on',
        slug: 'server-components-two-years-on',
        summary:
          'What React Server Components actually changed about how I build product UI — and the three places I still reach for state on the client.',
        tags: ['next.js', 'react', 'architecture'],
        published: true,
        createdAt: '2025-09-24T09:00:00.000Z',
        updatedAt: '2026-01-10T09:00:00.000Z',
        image: cover('server-components-two-years'),
        content: [
          'Two years into writing RSC product code, the interesting question is no longer "can it render on the server". It is where the seam should be.',
          '',
          '## What genuinely got better',
          '',
          '- **Data fetching went back to the component that owns it.** No more loader files that mirror the route tree and a store that caches their output.',
          '- **Bundles shrank without trying.** The chart library, the Markdown renderer and the date formatting live server-side now; a page that shows a chart ships the chart, not the library.',
          '- **Permission logic has one home.** Rendering a field that should not be visible stopped being a client-side problem.',
          '',
          '## Where I still want client state',
          '',
          '1. **Anything with a cursor.** Drag, resize, text selection — interactions that fire sixty times a second do not belong in a server round trip.',
          '2. **Optimistic forms.** A field that must feel instant writes locally first and reconciles after.',
          '3. **Cross-component ephemera.** Command palettes, focus management, toast queues. Small stores, no persistence, and I keep them in one folder so nobody mistakes them for architecture.',
          '',
          '## The mistake worth naming',
          '',
          "The eager `'use client'` at the top of a shared component. One import of a hook moves a whole subtree into the client bundle and the tree-shaking story dies quietly. Our lint rule now flags a client boundary above sixty lines; the fix is almost always to push the interactive leaf down instead of lifting the shell up.",
          '',
          '## Short version',
          '',
          'Server by default, client where the cursor is. And the seam is a design decision worth arguing about once, in writing, rather than one you rediscover in every pull request.',
        ].join('\n'),
      },
      {
        title: 'Building this portfolio: monochrome, bilingual, boring on purpose',
        slug: 'building-this-portfolio',
        summary: 'The rules behind the site you are reading: no colour, one data layer, two locales, one command to deploy.',
        tags: ['next.js', 'mongodb', 'design-system'],
        published: true,
        createdAt: '2025-07-18T09:00:00.000Z',
        image: cover('monochrome-build-notes'),
        content: [
          'This site is also a project, so it gets a post. Every choice in it came from one constraint: the work should be the most visible thing on the page.',
          '',
          '## No colour',
          '',
          'The palette is ink and paper, in two themes. Everything that would normally be communicated by colour — hover, focus, active section, draft state — is done with weight, borders and one pixel of offset. Colour is information you spend once; a monochrome palette spends nothing.',
          '',
          '## Two locales, one tree',
          '',
          'English and Persian render from the same components. The trick is not next-intl, it is logical properties: `ps-4` instead of `pl-4`, `text-start` instead of `text-left`. Persian brings its own requirements — a different typeface, looser leading, tabular numerals switched to Persian digits — and each lives in the theme, not in a conditional.',
          '',
          '## Content is data, and data is safe to be missing',
          '',
          'Every section reads from MongoDB through one server-side layer that returns empty states when the database is unreachable. The site degrades to a well-shaped shell instead of a 500 page, which is the behaviour I want at 2 a.m. on a managed database with a bad day.',
          '',
          '## One command',
          '',
          '- `npm run seed` loads demo content, and skips itself if the database is not empty.',
          '- `npm run seed:force` resets it.',
          '- `npm run verify` runs lint, typecheck and build — the same gate CI runs.',
          '',
          'No database to stand up, no docker-compose, no eleven-step README. A template you cannot run in three commands is a template nobody customises.',
        ].join('\n'),
      },
      {
        title: 'Notes on pricing a side project',
        slug: 'notes-on-pricing-a-side-project',
        summary: 'Numbers, instincts and one uncomfortable email, from the first year of charging for Ledgerly.',
        tags: ['indie', 'pricing', 'career'],
        published: false,
        createdAt: '2026-07-30T09:00:00.000Z',
        image: cover('pricing-side-project'),
        content: [
          'Draft, mostly numbers I have not verified twice yet.',
          '',
          '- Free self-hosted, paid hosted: the split that made pricing easy. The feature set is identical; what costs money is my time.',
          '- €9/month was the first number and roughly the right one. Doubling it did not halve conversions — tripling it did.',
          '- The uncomfortable email: a freelancer who could not pay. The answer was a free account and a link to the self-hosted build, and it took four minutes.',
          '- Churn is not a funnel problem when the product solves a monthly chore. It is seasonal: January is the best month of the year.',
          '',
          'To finish: what happens when a subscriber stops invoicing at all — they keep paying for a thing they use zero times, and I do not know whether that is a good deal or a bad one.',
        ].join('\n'),
      },
    ],
    fa: [
      {
        title: 'مهاجرت Prisma در production: قوانینی که یک بار شکستیم',
        slug: 'prisma-migrations-in-production',
        summary: 'یک تغییر schema، اپ فاکتور را یازده دقیقه از دسترس خارج کرد. runbookی که بعد از آن نوشتیم و چهار قانونی که کار به آن‌ها رسید.',
        tags: ['postgresql', 'prisma', 'devops'],
        published: true,
        createdAt: '2026-02-11T09:00:00.000Z',
        image: cover('prisma-migrations'),
        content: [
          'یازده دقیقه قطعی، برای تغییری که فقط یک ستون اضافه می‌کرد. خود مهاجرت درست بود؛ ترتیب عملیات نبود. این همان نوشته‌ای است که کاش قبل از آن بعدازظهر خوانده بودمش.',
          '',
          '## چه اتفاقی افتاد',
          '',
          '`prisma migrate deploy` سه دستور را در یک تراکنش پیچید: افزودن ستون، backfill با مقدار پیش‌فرض و بعد ساخت یک unique index. آن backfill روی جدولی شلوغ قفل گرفت، ساخت ایندکس منتظرش ماند و هر نوشتنِ پشت سر مثل ترافیک پشت یک تصادف در صف نشست.',
          '',
          '## قوانینی که از آن بیرون آمد',
          '',
          '۱. **افزودنی را از حذف‌کردنی جدا کن.** یک مهاجرت یا چیزی اضافه می‌کند یا چیزی حذف؛ حذف ریلیز مستقل خودش را دارد، بعد از آنکه دیگر چیزی به شکل قدسی ننویسد.',
          '۲. **هرگز داخل مهاجرت backfill نکن.** کاری دسته‌ای که می‌توانی مکثش کنی، بهتر از قفلی است که نمی‌توانی قطعش کنی.',
          '۳. **ایندکس را بیرون از تراکنش بساز.** `CREATE INDEX CONCURRENTLY` در یک گام خام؛ Prisma پشتیبانی‌اش می‌کند و قفل نوشتن نگه نمی‌دارد.',
          '۴. **از شکل جدید بخوان، به هر دو بنویس، بعد فقط از جدید بخوان.** سه دیپلوی برای هر تغییر شکننده. کند به نظر می‌رسد، تا زمانی که دومی را انجام ندهی.',
          '',
          '## بخشی که کسی درباره‌اش هشدار نمی‌دهد',
          '',
          'تاریخچه مهاجرت یک فایل مشترک با استراتژی merge است که مالکی ندارد. دو برنج، دو `migration.sql` و یک تعارض که هرکس آخر rebase کرده حلش می‌کند. حالا در CI `prisma migrate diff` را روی shadow database اجرا می‌کنیم، تا هر واگرایی بین schema و تاریخچه، پیش از اینکه production را از کار بیندازد، PR را رد کند.',
        ].join('\n'),
      },
      {
        title: 'React Server Components، دو سال بعد',
        slug: 'server-components-two-years-on',
        summary: 'RSC واقعاً چه چیزی را در ساخت رابط محصول عوض کرد — و سه جایی که هنوز می‌روم سراغ state سمت کاربر.',
        tags: ['next.js', 'react', 'architecture'],
        published: true,
        createdAt: '2025-09-24T09:00:00.000Z',
        updatedAt: '2026-01-10T09:00:00.000Z',
        image: cover('server-components-two-years'),
        content: [
          'دو سال بعد از نوشتن کد محصول با RSC، سؤال جالب «آیا می‌شود سمت سرور رندر کرد» دیگر مطرح نیست؛ سؤال این است درز کجا باید باشد.',
          '',
          '## چه چیزی واقعاً بهتر شد',
          '',
          '- **fetch داده برگشت به همان کامپوننتی که مالکش است.** دیگر فایل loader آینه درخت route نیست و یک store هم خروجی آن‌ها را کش نمی‌کند.',
          '- **باندل بدون تلاش کوچک‌تر شد.** کتابخانه چارت، رندر Markdown و قالب‌سازی تاریخ حالا سمت سرورند؛ صفحه‌ای که یک نمودار نشان می‌دهد نمودار را می‌فرستد، نه کتابخانه را.',
          '- **منطق دسترسی یک خانه دارد.** رندر نشدن فیلدی که نباید دیده شود، دیگر مسئله سمت کاربر نیست.',
          '',
          '## کجاها هنوز state سمت کاربر می‌خواهم',
          '',
          '۱. **هر چیزی که cursor دارد.** درگ، ریسایز و انتخاب متن؛ تعاملی که ثانیه‌ای شصت بار fire می‌شود جای آن در یک رفت‌وبرگشت سروری نیست.',
          '۲. **فورم خوش‌بینانه.** فیلدی که باید آنی حس شود، اول محلی می‌نویسد و بعد همگام می‌شود.',
          '۳. **چیزهای زودگذر بین کامپوننتی.** پالت دستور، مدیریت فوکوس و صف toast. استورهای کوچک بدون persist، در یک پوشه، تا کسی آن‌ها را معماری حساب نکند.',
          '',
          '## اشتباهی که اسم بردنش لازم است',
          '',
          "`'use client'` بی‌دلیل بالای یک کامپوننت مشترک. یک import از یک hook کل زیردرخت را به باندل کلاینت می‌برد و tree-shaking بی‌صدا می‌میرد. قانون lint ما حالا مرز کلاینت بزرگ‌تر از شصت خط را علامت می‌زند؛ راه‌حل تقریباً همیشه این است که برگه تعاملی را پایین ببریم، نه پوسته را بالا.",
        ].join('\n'),
      },
      {
        title: 'ساخت این نمونه‌کار: مونوکروم، دوزبانه و عمداً کسل‌کننده',
        slug: 'building-this-portfolio',
        summary: 'قوانین پشت سایتی که می‌خوانید: بدون رنگ، یک لایه داده، دو زبان و یک دستور برای دیپلوی.',
        tags: ['next.js', 'mongodb', 'design-system'],
        published: true,
        createdAt: '2025-07-18T09:00:00.000Z',
        image: cover('monochrome-build-notes'),
        content: [
          'این سایت خودش یک پروژه است، پس یک پست هم می‌گیرد. هر انتخاب در آن از یک محدودیت می‌آید: قابل‌مشاهده‌ترین چیز صفحه باید کار باشد، نه تزئیناتش.',
          '',
          '## بدون رنگ',
          '',
          'پالت، مرکب و کاغذ است، در دو تم. هر چیزی که معمولاً با رنگ رسانده می‌شود — hover، فوکوس، بخش فعال، حالت پیش‌نویس — با وزن، خط و یک پیکسل جابه‌جایی انجام می‌شود. رنگ اطلاعاتی است که یک بار خرجش می‌کنی؛ پالت مونوکروم هیچ خرج نمی‌کند.',
          '',
          '## دو زبان، یک درخت',
          '',
          'انگلیسی و فارسی از همان کامپوننت‌ها رندر می‌شوند. ترفند next-intl نیست، خاصیت‌های منطقی‌اند: `ps-4` به‌جای `pl-4` و `text-start` به‌جای `text-left`. فارسی الزام‌های خودش را می‌آورد — فونت دیگر، فاصله خطوط بیشتر و ارقام فارسی به‌جای ارقام tabular — و هرکدام در تم زندگی می‌کند، نه در یک شرط.',
          '',
          '## محتوا داده است و داده می‌تواند نباشد',
          '',
          'هر بخش از MongoDB و از یک لایه سمت سرور می‌خواند که وقتی دیتابیس در دسترس نیست، حالت خالی برمی‌گرداند. سایت به‌جای صفحه ۵۰۰، به یک پوسته خوش‌ساخت تنزل می‌کند؛ همان رفتاری که ساعت دو بامداد، پای یک دیتابیس managed با روز بد می‌خواهم.',
          '',
          '## یک دستور',
          '',
          '- `npm run seed` محتوای نمونه را بارگذاری می‌کند و اگر دیتابیس خالی نباشد، خودش را رد می‌کند.',
          '- `npm run seed:force` آن را بازنشانی می‌کند.',
          '- `npm run verify` لینت، تایپ‌چک و بیلد را با هم اجرا می‌کند؛ همان گیتی که CI اجرا می‌کند.',
          '',
          'بدون دیتابیسی که بالا بیاوری، بدون docker-compose و بدون README یازده‌مرحله‌ای. تمپلیتی که در سه دستور اجرا نشود، تمپلیتی است که کسی شخصی‌سازی‌اش نمی‌کند.',
        ].join('\n'),
      },
      {
        title: 'یادداشت‌هایی درباره قیمت‌گذاری یک پروژه جانبی',
        slug: 'notes-on-pricing-a-side-project',
        summary: 'اعداد، حدس‌ها و یک ایمیل ناراحت‌کننده، از سال اول پول گرفتن بابت لجرلی.',
        tags: ['indie', 'pricing', 'career'],
        published: false,
        createdAt: '2026-07-30T09:00:00.000Z',
        image: cover('pricing-side-project'),
        content: [
          'پیش‌نویس؛ بیشتر اعداد هنوز دوبار چک نشده‌اند.',
          '',
          '- خودمیزبان رایگان، میزبانی‌شده پولی: همان تقسیمی که قیمت‌گذاری را آسان کرد. مجموعه قابلیت‌ها عیناً یکی است؛ چیزی که پول می‌گیرد وقت من است.',
          '- ۹ یورو در ماه عدد اول بود و تقریباً عدد درست. دو برابرش تبدیل را نصف نکرد؛ سه برابرش کرد.',
          '- آن ایمیل ناراحت‌کننده: فریلنسری که توان پرداخت نداشت. جواب یک حساب رایگان و یک لینک به بیلد خودمیزبان بود و چهار دقیقه وقت برد.',
          '- وقتی محصول یک کار ماهانه را حل می‌کند، churn مشکل قیف نیست؛ فصلی است: ژانویه بهترین ماه سال است.',
          '',
          'برای تمام کردن: چه می‌شود وقتی یک مشترک کلاً فاکتور صادر نمی‌کند؟ برای چیزی که صفر بار استفاده می‌کند همچنان پول می‌دهد و من نمی‌دانم این معامله خوب است یا بد.',
        ].join('\n'),
      },
    ],
  },
};
